/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountCustomDataRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.AccountCustomDataRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -295774737;

	/**
	 * Setter for <code>Account.accountCustomData.accountId</code>.
	 */
	public void setAccountId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.accountCustomData.accountId</code>.
	 */
	public java.lang.Integer getAccountId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.accountCustomData.customDataId</code>.
	 */
	public void setCustomDataId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.accountCustomData.customDataId</code>.
	 */
	public java.lang.Integer getCustomDataId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.accountCustomData.data</code>.
	 */
	public void setData(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.accountCustomData.data</code>.
	 */
	public java.lang.Integer getData() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.AccountCustomData.accountCustomData.accountId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.AccountCustomData.accountCustomData.customDataId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return mineplex.database.tables.AccountCustomData.accountCustomData.data;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCustomDataId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountCustomDataRecord value1(java.lang.Integer value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountCustomDataRecord value2(java.lang.Integer value) {
		setCustomDataId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountCustomDataRecord value3(java.lang.Integer value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountCustomDataRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AccountCustomDataRecord
	 */
	public AccountCustomDataRecord() {
		super(mineplex.database.tables.AccountCustomData.accountCustomData);
	}

	/**
	 * Create a detached, initialised AccountCustomDataRecord
	 */
	public AccountCustomDataRecord(java.lang.Integer accountId, java.lang.Integer customDataId, java.lang.Integer data) {
		super(mineplex.database.tables.AccountCustomData.accountCustomData);

		setValue(0, accountId);
		setValue(1, customDataId);
		setValue(2, data);
	}
}
