/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountValentinesGiftRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.AccountValentinesGiftRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = -117314610;

	/**
	 * Setter for <code>Account.accountValentinesGift.senderId</code>.
	 */
	public void setSenderId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.accountValentinesGift.senderId</code>.
	 */
	public java.lang.Integer getSenderId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.accountValentinesGift.targetId</code>.
	 */
	public void setTargetId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.accountValentinesGift.targetId</code>.
	 */
	public java.lang.Integer getTargetId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.accountValentinesGift.time</code>.
	 */
	public void setTime(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.accountValentinesGift.time</code>.
	 */
	public java.sql.Timestamp getTime() {
		return (java.sql.Timestamp) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.AccountValentinesGift.accountValentinesGift.senderId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.AccountValentinesGift.accountValentinesGift.targetId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return mineplex.database.tables.AccountValentinesGift.accountValentinesGift.time;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getSenderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTargetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountValentinesGiftRecord value1(java.lang.Integer value) {
		setSenderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountValentinesGiftRecord value2(java.lang.Integer value) {
		setTargetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountValentinesGiftRecord value3(java.sql.Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountValentinesGiftRecord values(java.lang.Integer value1, java.lang.Integer value2, java.sql.Timestamp value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AccountValentinesGiftRecord
	 */
	public AccountValentinesGiftRecord() {
		super(mineplex.database.tables.AccountValentinesGift.accountValentinesGift);
	}

	/**
	 * Create a detached, initialised AccountValentinesGiftRecord
	 */
	public AccountValentinesGiftRecord(java.lang.Integer senderId, java.lang.Integer targetId, java.sql.Timestamp time) {
		super(mineplex.database.tables.AccountValentinesGift.accountValentinesGift);

		setValue(0, senderId);
		setValue(1, targetId);
		setValue(2, time);
	}
}
