/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountPreferencesRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.AccountPreferencesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1681212593;

	/**
	 * Setter for <code>Account.accountPreferences.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.accountPreferences.uuid</code>.
	 */
	public void setUuid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.uuid</code>.
	 */
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Account.accountPreferences.filterChat</code>.
	 */
	public void setFilterChat(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.filterChat</code>.
	 */
	public java.lang.Byte getFilterChat() {
		return (java.lang.Byte) getValue(2);
	}

	/**
	 * Setter for <code>Account.accountPreferences.invisibility</code>.
	 */
	public void setInvisibility(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.invisibility</code>.
	 */
	public java.lang.Byte getInvisibility() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>Account.accountPreferences.games</code>.
	 */
	public void setGames(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.games</code>.
	 */
	public java.lang.Byte getGames() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>Account.accountPreferences.visibility</code>.
	 */
	public void setVisibility(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.visibility</code>.
	 */
	public java.lang.Byte getVisibility() {
		return (java.lang.Byte) getValue(5);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendChat</code>.
	 */
	public void setFriendChat(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendChat</code>.
	 */
	public java.lang.Byte getFriendChat() {
		return (java.lang.Byte) getValue(6);
	}

	/**
	 * Setter for <code>Account.accountPreferences.privateMessaging</code>.
	 */
	public void setPrivateMessaging(java.lang.Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.privateMessaging</code>.
	 */
	public java.lang.Byte getPrivateMessaging() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>Account.accountPreferences.showChat</code>.
	 */
	public void setShowChat(java.lang.Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.showChat</code>.
	 */
	public java.lang.Byte getShowChat() {
		return (java.lang.Byte) getValue(8);
	}

	/**
	 * Setter for <code>Account.accountPreferences.partyRequests</code>.
	 */
	public void setPartyRequests(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.partyRequests</code>.
	 */
	public java.lang.Byte getPartyRequests() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>Account.accountPreferences.forcefield</code>.
	 */
	public void setForcefield(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.forcefield</code>.
	 */
	public java.lang.Byte getForcefield() {
		return (java.lang.Byte) getValue(10);
	}

	/**
	 * Setter for <code>Account.accountPreferences.showMacReports</code>.
	 */
	public void setShowMacReports(java.lang.Byte value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.showMacReports</code>.
	 */
	public java.lang.Byte getShowMacReports() {
		return (java.lang.Byte) getValue(11);
	}

	/**
	 * Setter for <code>Account.accountPreferences.ignoreVelocity</code>.
	 */
	public void setIgnoreVelocity(java.lang.Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.ignoreVelocity</code>.
	 */
	public java.lang.Byte getIgnoreVelocity() {
		return (java.lang.Byte) getValue(12);
	}

	/**
	 * Setter for <code>Account.accountPreferences.pendingFriendRequests</code>.
	 */
	public void setPendingFriendRequests(java.lang.Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.pendingFriendRequests</code>.
	 */
	public java.lang.Byte getPendingFriendRequests() {
		return (java.lang.Byte) getValue(13);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendDisplayInventoryUI</code>.
	 */
	public void setFriendDisplayInventoryUI(java.lang.Byte value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendDisplayInventoryUI</code>.
	 */
	public java.lang.Byte getFriendDisplayInventoryUI() {
		return (java.lang.Byte) getValue(14);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendDisplayOnlineStatus</code>.
	 */
	public void setFriendDisplayOnlineStatus(java.lang.Byte value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendDisplayOnlineStatus</code>.
	 */
	public java.lang.Byte getFriendDisplayOnlineStatus() {
		return (java.lang.Byte) getValue(15);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendDisplayServerName</code>.
	 */
	public void setFriendDisplayServerName(java.lang.Byte value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendDisplayServerName</code>.
	 */
	public java.lang.Byte getFriendDisplayServerName() {
		return (java.lang.Byte) getValue(16);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendAllowRequests</code>.
	 */
	public void setFriendAllowRequests(java.lang.Byte value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendAllowRequests</code>.
	 */
	public java.lang.Byte getFriendAllowRequests() {
		return (java.lang.Byte) getValue(17);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendAllowMessaging</code>.
	 */
	public void setFriendAllowMessaging(java.lang.Byte value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendAllowMessaging</code>.
	 */
	public java.lang.Byte getFriendAllowMessaging() {
		return (java.lang.Byte) getValue(18);
	}

	/**
	 * Setter for <code>Account.accountPreferences.clanTips</code>.
	 */
	public void setClanTips(java.lang.Byte value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.clanTips</code>.
	 */
	public java.lang.Byte getClanTips() {
		return (java.lang.Byte) getValue(19);
	}

	/**
	 * Setter for <code>Account.accountPreferences.language</code>.
	 */
	public void setLanguage(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.language</code>.
	 */
	public java.lang.String getLanguage() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>Account.accountPreferences.showUserReports</code>.
	 */
	public void setShowUserReports(java.lang.Byte value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.showUserReports</code>.
	 */
	public java.lang.Byte getShowUserReports() {
		return (java.lang.Byte) getValue(21);
	}

	/**
	 * Setter for <code>Account.accountPreferences.hubMusic</code>.
	 */
	public void setHubMusic(java.lang.Byte value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.hubMusic</code>.
	 */
	public java.lang.Byte getHubMusic() {
		return (java.lang.Byte) getValue(22);
	}

	/**
	 * Setter for <code>Account.accountPreferences.disableAds</code>.
	 */
	public void setDisableAds(java.lang.Byte value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.disableAds</code>.
	 */
	public java.lang.Byte getDisableAds() {
		return (java.lang.Byte) getValue(23);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AccountPreferencesRecord
	 */
	public AccountPreferencesRecord() {
		super(mineplex.database.tables.AccountPreferences.accountPreferences);
	}

	/**
	 * Create a detached, initialised AccountPreferencesRecord
	 */
	public AccountPreferencesRecord(java.lang.Integer id, java.lang.String uuid, java.lang.Byte filterChat, java.lang.Byte invisibility, java.lang.Byte games, java.lang.Byte visibility, java.lang.Byte friendChat, java.lang.Byte privateMessaging, java.lang.Byte showChat, java.lang.Byte partyRequests, java.lang.Byte forcefield, java.lang.Byte showMacReports, java.lang.Byte ignoreVelocity, java.lang.Byte pendingFriendRequests, java.lang.Byte friendDisplayInventoryUI, java.lang.Byte friendDisplayOnlineStatus, java.lang.Byte friendDisplayServerName, java.lang.Byte friendAllowRequests, java.lang.Byte friendAllowMessaging, java.lang.Byte clanTips, java.lang.String language, java.lang.Byte showUserReports, java.lang.Byte hubMusic, java.lang.Byte disableAds) {
		super(mineplex.database.tables.AccountPreferences.accountPreferences);

		setValue(0, id);
		setValue(1, uuid);
		setValue(2, filterChat);
		setValue(3, invisibility);
		setValue(4, games);
		setValue(5, visibility);
		setValue(6, friendChat);
		setValue(7, privateMessaging);
		setValue(8, showChat);
		setValue(9, partyRequests);
		setValue(10, forcefield);
		setValue(11, showMacReports);
		setValue(12, ignoreVelocity);
		setValue(13, pendingFriendRequests);
		setValue(14, friendDisplayInventoryUI);
		setValue(15, friendDisplayOnlineStatus);
		setValue(16, friendDisplayServerName);
		setValue(17, friendAllowRequests);
		setValue(18, friendAllowMessaging);
		setValue(19, clanTips);
		setValue(20, language);
		setValue(21, showUserReports);
		setValue(22, hubMusic);
		setValue(23, disableAds);
	}
}
