/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BonusRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.BonusRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record11<java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Date, java.sql.Date, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -785434679;

	/**
	 * Setter for <code>Account.bonus.accountId</code>.
	 */
	public void setAccountId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.bonus.accountId</code>.
	 */
	public java.lang.Integer getAccountId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.bonus.dailytime</code>.
	 */
	public void setDailytime(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.bonus.dailytime</code>.
	 */
	public java.sql.Timestamp getDailytime() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>Account.bonus.clansdailytime</code>.
	 */
	public void setClansDailytime(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.bonus.clansdailytime</code>.
	 */
	public java.sql.Timestamp getClansDailytime() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>Account.bonus.ranktime</code>.
	 */
	public void setRanktime(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.bonus.ranktime</code>.
	 */
	public java.sql.Date getRanktime() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>Account.bonus.votetime</code>.
	 */
	public void setVotetime(java.sql.Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.bonus.votetime</code>.
	 */
	public java.sql.Date getVotetime() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>Account.bonus.clansvotetime</code>.
	 */
	public void setClansVotetime(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.bonus.votetime</code>.
	 */
	public java.sql.Date getClansVotetime() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>Account.bonus.dailyStreak</code>.
	 */
	public void setDailyStreak(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.bonus.dailyStreak</code>.
	 */
	public java.lang.Integer getDailyStreak() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>Account.bonus.maxDailyStreak</code>.
	 */
	public void setMaxDailyStreak(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>Account.bonus.maxDailyStreak</code>.
	 */
	public java.lang.Integer getMaxDailyStreak() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>Account.bonus.voteStreak</code>.
	 */
	public void setVoteStreak(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>Account.bonus.voteStreak</code>.
	 */
	public java.lang.Integer getVoteStreak() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>Account.bonus.maxVoteStreak</code>.
	 */
	public void setMaxVoteStreak(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>Account.bonus.maxVoteStreak</code>.
	 */
	public java.lang.Integer getMaxVoteStreak() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>Account.bonus.tickets</code>.
	 */
	public void setTickets(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>Account.bonus.tickets</code>.
	 */
	public java.lang.Integer getTickets() {
		return (java.lang.Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Date, java.sql.Date, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Date, java.sql.Date, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.Bonus.bonus.accountId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return mineplex.database.tables.Bonus.bonus.dailytime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return mineplex.database.tables.Bonus.bonus.clansdailytime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return mineplex.database.tables.Bonus.bonus.ranktime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return mineplex.database.tables.Bonus.bonus.votetime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return mineplex.database.tables.Bonus.bonus.clansvotetime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return mineplex.database.tables.Bonus.bonus.dailyStreak;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return mineplex.database.tables.Bonus.bonus.maxDailyStreak;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return mineplex.database.tables.Bonus.bonus.voteStreak;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return mineplex.database.tables.Bonus.bonus.maxVoteStreak;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return mineplex.database.tables.Bonus.bonus.tickets;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getDailytime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getClansDailytime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getRanktime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getVotetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getClansVotetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getDailyStreak();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getMaxDailyStreak();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getVoteStreak();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getMaxVoteStreak();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getTickets();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value1(java.lang.Integer value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value2(java.sql.Timestamp value) {
		setDailytime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value3(java.sql.Timestamp value) {
		setClansDailytime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value4(java.sql.Date value) {
		setRanktime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value5(java.sql.Date value) {
		setVotetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value6(java.sql.Date value) {
		setClansVotetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value7(java.lang.Integer value) {
		setDailyStreak(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value8(java.lang.Integer value) {
		setMaxDailyStreak(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value9(java.lang.Integer value) {
		setVoteStreak(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value10(java.lang.Integer value) {
		setMaxVoteStreak(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord value11(java.lang.Integer value) {
		setTickets(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusRecord values(java.lang.Integer value1, java.sql.Timestamp value2, java.sql.Timestamp value3, java.sql.Date value4, java.sql.Date value5, java.sql.Date value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Integer value10, java.lang.Integer value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BonusRecord
	 */
	public BonusRecord() {
		super(mineplex.database.tables.Bonus.bonus);
	}

	/**
	 * Create a detached, initialised BonusRecord
	 */
	public BonusRecord(java.lang.Integer accountId, java.sql.Timestamp dailytime, java.sql.Timestamp clansdailytime, java.sql.Date ranktime, java.sql.Date votetime, java.sql.Date clansvotetime, java.lang.Integer dailyStreak, java.lang.Integer maxDailyStreak, java.lang.Integer voteStreak, java.lang.Integer maxVoteStreak, java.lang.Integer tickets) {
		super(mineplex.database.tables.Bonus.bonus);

		setValue(0, accountId);
		setValue(1, dailytime);
		setValue(2, clansdailytime);
		setValue(3, ranktime);
		setValue(4, votetime);
		setValue(5, clansvotetime);
		setValue(6, dailyStreak);
		setValue(7, maxDailyStreak);
		setValue(8, voteStreak);
		setValue(9, maxVoteStreak);
		setValue(10, tickets);
	}
}
