/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BonusLogRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.BonusLogRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = -918833180;

	/**
	 * Setter for <code>Account.bonusLog.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.bonusLog.accountId</code>.
	 */
	public void setAccountId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.accountId</code>.
	 */
	public java.lang.Integer getAccountId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.bonusLog.gemChange</code>.
	 */
	public void setGemChange(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.gemChange</code>.
	 */
	public java.lang.Integer getGemChange() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>Account.bonusLog.coinChange</code>.
	 */
	public void setCoinChange(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.coinChange</code>.
	 */
	public java.lang.Integer getCoinChange() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>Account.bonusLog.itemId</code>.
	 */
	public void setItemId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.itemId</code>.
	 */
	public java.lang.Integer getItemId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>Account.bonusLog.itemChange</code>.
	 */
	public void setItemChange(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.itemChange</code>.
	 */
	public java.lang.Integer getItemChange() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>Account.bonusLog.time</code>.
	 */
	public void setTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.bonusLog.time</code>.
	 */
	public java.sql.Timestamp getTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.BonusLog.bonusLog.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.BonusLog.bonusLog.accountId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return mineplex.database.tables.BonusLog.bonusLog.gemChange;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return mineplex.database.tables.BonusLog.bonusLog.coinChange;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return mineplex.database.tables.BonusLog.bonusLog.itemId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return mineplex.database.tables.BonusLog.bonusLog.itemChange;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return mineplex.database.tables.BonusLog.bonusLog.time;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getGemChange();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCoinChange();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getItemChange();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value2(java.lang.Integer value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value3(java.lang.Integer value) {
		setGemChange(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value4(java.lang.Integer value) {
		setCoinChange(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value5(java.lang.Integer value) {
		setItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value6(java.lang.Integer value) {
		setItemChange(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord value7(java.sql.Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BonusLogRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BonusLogRecord
	 */
	public BonusLogRecord() {
		super(mineplex.database.tables.BonusLog.bonusLog);
	}

	/**
	 * Create a detached, initialised BonusLogRecord
	 */
	public BonusLogRecord(java.lang.Integer id, java.lang.Integer accountId, java.lang.Integer gemChange, java.lang.Integer coinChange, java.lang.Integer itemId, java.lang.Integer itemChange, java.sql.Timestamp time) {
		super(mineplex.database.tables.BonusLog.bonusLog);

		setValue(0, id);
		setValue(1, accountId);
		setValue(2, gemChange);
		setValue(3, coinChange);
		setValue(4, itemId);
		setValue(5, itemChange);
		setValue(6, time);
	}
}
