/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BotSpamRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.BotSpamRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -818870436;

	/**
	 * Setter for <code>Account.botSpam.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.botSpam.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.botSpam.text</code>.
	 */
	public void setText(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.botSpam.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Account.botSpam.punishments</code>.
	 */
	public void setPunishments(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.botSpam.punishments</code>.
	 */
	public java.lang.Integer getPunishments() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>Account.botSpam.enabled</code>.
	 */
	public void setEnabled(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.botSpam.enabled</code>.
	 */
	public java.lang.Byte getEnabled() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>Account.botSpam.createdBy</code>.
	 */
	public void setCreatedBy(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.botSpam.createdBy</code>.
	 */
	public java.lang.String getCreatedBy() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>Account.botSpam.enabledBy</code>.
	 */
	public void setEnabledBy(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.botSpam.enabledBy</code>.
	 */
	public java.lang.String getEnabledBy() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>Account.botSpam.disabledBy</code>.
	 */
	public void setDisabledBy(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.botSpam.disabledBy</code>.
	 */
	public java.lang.String getDisabledBy() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.BotSpam.botSpam.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return mineplex.database.tables.BotSpam.botSpam.text;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return mineplex.database.tables.BotSpam.botSpam.punishments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return mineplex.database.tables.BotSpam.botSpam.enabled;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return mineplex.database.tables.BotSpam.botSpam.createdBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return mineplex.database.tables.BotSpam.botSpam.enabledBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return mineplex.database.tables.BotSpam.botSpam.disabledBy;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPunishments();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getCreatedBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getEnabledBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDisabledBy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value2(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value3(java.lang.Integer value) {
		setPunishments(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value4(java.lang.Byte value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value5(java.lang.String value) {
		setCreatedBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value6(java.lang.String value) {
		setEnabledBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord value7(java.lang.String value) {
		setDisabledBy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BotSpamRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Byte value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BotSpamRecord
	 */
	public BotSpamRecord() {
		super(mineplex.database.tables.BotSpam.botSpam);
	}

	/**
	 * Create a detached, initialised BotSpamRecord
	 */
	public BotSpamRecord(java.lang.Integer id, java.lang.String text, java.lang.Integer punishments, java.lang.Byte enabled, java.lang.String createdBy, java.lang.String enabledBy, java.lang.String disabledBy) {
		super(mineplex.database.tables.BotSpam.botSpam);

		setValue(0, id);
		setValue(1, text);
		setValue(2, punishments);
		setValue(3, enabled);
		setValue(4, createdBy);
		setValue(5, enabledBy);
		setValue(6, disabledBy);
	}
}
