/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsnapRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.ChatsnapRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 2087133341;

	/**
	 * Setter for <code>Account.chatsnap.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.chatsnap.reporterId</code>.
	 */
	public void setReporterId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.reporterId</code>.
	 */
	public java.lang.Integer getReporterId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.chatsnap.reporteeId</code>.
	 */
	public void setReporteeId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.reporteeId</code>.
	 */
	public java.lang.Integer getReporteeId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>Account.chatsnap.time</code>.
	 */
	public void setTime(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.time</code>.
	 */
	public java.sql.Timestamp getTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>Account.chatsnap.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>Account.chatsnap.reason</code>.
	 */
	public void setReason(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.reason</code>.
	 */
	public java.lang.String getReason() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>Account.chatsnap.data</code>.
	 */
	public void setData(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.chatsnap.data</code>.
	 */
	public java.lang.String getData() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.Chatsnap.chatsnap.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.Chatsnap.chatsnap.reporterId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return mineplex.database.tables.Chatsnap.chatsnap.reporteeId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return mineplex.database.tables.Chatsnap.chatsnap.time;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return mineplex.database.tables.Chatsnap.chatsnap.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return mineplex.database.tables.Chatsnap.chatsnap.reason;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return mineplex.database.tables.Chatsnap.chatsnap.data;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getReporterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getReporteeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getReason();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value2(java.lang.Integer value) {
		setReporterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value3(java.lang.Integer value) {
		setReporteeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value4(java.sql.Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value5(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value6(java.lang.String value) {
		setReason(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord value7(java.lang.String value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ChatsnapRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.sql.Timestamp value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChatsnapRecord
	 */
	public ChatsnapRecord() {
		super(mineplex.database.tables.Chatsnap.chatsnap);
	}

	/**
	 * Create a detached, initialised ChatsnapRecord
	 */
	public ChatsnapRecord(java.lang.Integer id, java.lang.Integer reporterId, java.lang.Integer reporteeId, java.sql.Timestamp time, java.lang.String status, java.lang.String reason, java.lang.String data) {
		super(mineplex.database.tables.Chatsnap.chatsnap);

		setValue(0, id);
		setValue(1, reporterId);
		setValue(2, reporteeId);
		setValue(3, time);
		setValue(4, status);
		setValue(5, reason);
		setValue(6, data);
	}
}
