/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanTerritoryRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.ClanTerritoryRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = -790523351;

	/**
	 * Setter for <code>Account.clanTerritory.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.clanTerritory.clanId</code>.
	 */
	public void setClanId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.clanId</code>.
	 */
	public java.lang.Integer getClanId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.clanTerritory.chunk</code>.
	 */
	public void setChunk(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.chunk</code>.
	 */
	public java.lang.String getChunk() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>Account.clanTerritory.safe</code>.
	 */
	public void setSafe(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.safe</code>.
	 */
	public java.lang.Boolean getSafe() {
		return (java.lang.Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.ClanTerritory.clanTerritory.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.ClanTerritory.clanTerritory.clanId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return mineplex.database.tables.ClanTerritory.clanTerritory.chunk;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return mineplex.database.tables.ClanTerritory.clanTerritory.safe;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getClanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getChunk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getSafe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value2(java.lang.Integer value) {
		setClanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value3(java.lang.String value) {
		setChunk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value4(java.lang.Boolean value) {
		setSafe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.Boolean value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClanTerritoryRecord
	 */
	public ClanTerritoryRecord() {
		super(mineplex.database.tables.ClanTerritory.clanTerritory);
	}

	/**
	 * Create a detached, initialised ClanTerritoryRecord
	 */
	public ClanTerritoryRecord(java.lang.Integer id, java.lang.Integer clanId, java.lang.String chunk, java.lang.Boolean safe) {
		super(mineplex.database.tables.ClanTerritory.clanTerritory);

		setValue(0, id);
		setValue(1, clanId);
		setValue(2, chunk);
		setValue(3, safe);
	}
}
