/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansNetherPortalsRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.ClansNetherPortalsRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte> {

	private static final long serialVersionUID = -1366559485;

	/**
	 * Setter for <code>Account.clansNetherPortals.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.clansNetherPortals.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.clansNetherPortals.cornerOne</code>.
	 */
	public void setCornerOne(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.clansNetherPortals.cornerOne</code>.
	 */
	public java.lang.String getCornerOne() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Account.clansNetherPortals.cornerTwo</code>.
	 */
	public void setCornerTwo(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.clansNetherPortals.cornerTwo</code>.
	 */
	public java.lang.String getCornerTwo() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>Account.clansNetherPortals.returnPortal</code>.
	 */
	public void setReturnPortal(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.clansNetherPortals.returnPortal</code>.
	 */
	public java.lang.Byte getReturnPortal() {
		return (java.lang.Byte) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Byte> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.ClansNetherPortals.clansNetherPortals.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return mineplex.database.tables.ClansNetherPortals.clansNetherPortals.cornerOne;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return mineplex.database.tables.ClansNetherPortals.clansNetherPortals.cornerTwo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return mineplex.database.tables.ClansNetherPortals.clansNetherPortals.returnPortal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCornerOne();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCornerTwo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getReturnPortal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansNetherPortalsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansNetherPortalsRecord value2(java.lang.String value) {
		setCornerOne(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansNetherPortalsRecord value3(java.lang.String value) {
		setCornerTwo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansNetherPortalsRecord value4(java.lang.Byte value) {
		setReturnPortal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansNetherPortalsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Byte value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClansNetherPortalsRecord
	 */
	public ClansNetherPortalsRecord() {
		super(mineplex.database.tables.ClansNetherPortals.clansNetherPortals);
	}

	/**
	 * Create a detached, initialised ClansNetherPortalsRecord
	 */
	public ClansNetherPortalsRecord(java.lang.Integer id, java.lang.String cornerOne, java.lang.String cornerTwo, java.lang.Byte returnPortal) {
		super(mineplex.database.tables.ClansNetherPortals.clansNetherPortals);

		setValue(0, id);
		setValue(1, cornerOne);
		setValue(2, cornerTwo);
		setValue(3, returnPortal);
	}
}
