/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansOutpostsRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.ClansOutpostsRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Integer, java.lang.String, java.lang.Byte> {

	private static final long serialVersionUID = 924324186;

	/**
	 * Setter for <code>Account.clansOutposts.uniqueId</code>.
	 */
	public void setUniqueId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.uniqueId</code>.
	 */
	public java.lang.Integer getUniqueId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.clansOutposts.serverId</code>.
	 */
	public void setServerId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.serverId</code>.
	 */
	public java.lang.Integer getServerId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.clansOutposts.origin</code>.
	 */
	public void setOrigin(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.origin</code>.
	 */
	public java.lang.String getOrigin() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>Account.clansOutposts.outpostType</code>.
	 */
	public void setOutpostType(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.outpostType</code>.
	 */
	public java.lang.Byte getOutpostType() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>Account.clansOutposts.ownerClan</code>.
	 */
	public void setOwnerClan(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.ownerClan</code>.
	 */
	public java.lang.Integer getOwnerClan() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>Account.clansOutposts.timeSpawned</code>.
	 */
	public void setTimeSpawned(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.timeSpawned</code>.
	 */
	public java.lang.String getTimeSpawned() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>Account.clansOutposts.outpostState</code>.
	 */
	public void setOutpostState(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.clansOutposts.outpostState</code>.
	 */
	public java.lang.Byte getOutpostState() {
		return (java.lang.Byte) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Integer, java.lang.String, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Integer, java.lang.String, java.lang.Byte> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.uniqueId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.serverId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.origin;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.outpostType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.ownerClan;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.timeSpawned;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return mineplex.database.tables.ClansOutposts.clansOutposts.outpostState;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUniqueId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getServerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOrigin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getOutpostType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getOwnerClan();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getTimeSpawned();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getOutpostState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value1(java.lang.Integer value) {
		setUniqueId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value2(java.lang.Integer value) {
		setServerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value3(java.lang.String value) {
		setOrigin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value4(java.lang.Byte value) {
		setOutpostType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value5(java.lang.Integer value) {
		setOwnerClan(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value6(java.lang.String value) {
		setTimeSpawned(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord value7(java.lang.Byte value) {
		setOutpostState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansOutpostsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.Byte value4, java.lang.Integer value5, java.lang.String value6, java.lang.Byte value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClansOutpostsRecord
	 */
	public ClansOutpostsRecord() {
		super(mineplex.database.tables.ClansOutposts.clansOutposts);
	}

	/**
	 * Create a detached, initialised ClansOutpostsRecord
	 */
	public ClansOutpostsRecord(java.lang.Integer uniqueId, java.lang.Integer serverId, java.lang.String origin, java.lang.Byte outpostType, java.lang.Integer ownerClan, java.lang.String timeSpawned, java.lang.Byte outpostState) {
		super(mineplex.database.tables.ClansOutposts.clansOutposts);

		setValue(0, uniqueId);
		setValue(1, serverId);
		setValue(2, origin);
		setValue(3, outpostType);
		setValue(4, ownerClan);
		setValue(5, timeSpawned);
		setValue(6, outpostState);
	}
}
