/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansTutorialRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.ClansTutorialRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -2119347650;

	/**
	 * Setter for <code>Account.clansTutorial.uuid</code>.
	 */
	public void setUuid(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.clansTutorial.uuid</code>.
	 */
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>Account.clansTutorial.timesPlayed</code>.
	 */
	public void setTimesPlayed(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.clansTutorial.timesPlayed</code>.
	 */
	public java.lang.Integer getTimesPlayed() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return mineplex.database.tables.ClansTutorial.clansTutorial.uuid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return mineplex.database.tables.ClansTutorial.clansTutorial.timesPlayed;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTimesPlayed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansTutorialRecord value1(java.lang.String value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansTutorialRecord value2(java.lang.Integer value) {
		setTimesPlayed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClansTutorialRecord values(java.lang.String value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClansTutorialRecord
	 */
	public ClansTutorialRecord() {
		super(mineplex.database.tables.ClansTutorial.clansTutorial);
	}

	/**
	 * Create a detached, initialised ClansTutorialRecord
	 */
	public ClansTutorialRecord(java.lang.String uuid, java.lang.Integer timesPlayed) {
		super(mineplex.database.tables.ClansTutorial.clansTutorial);

		setValue(0, uuid);
		setValue(1, timesPlayed);
	}
}
