/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NonPremiumJoinMessageRecord extends org.jooq.impl.TableRecordImpl<mineplex.database.tables.records.NonPremiumJoinMessageRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = 988609111;

	/**
	 * Setter for <code>Account.nonPremiumJoinMessage.message</code>.
	 */
	public void setMessage(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.nonPremiumJoinMessage.message</code>.
	 */
	public java.lang.String getMessage() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return mineplex.database.tables.NonPremiumJoinMessage.nonPremiumJoinMessage.message;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NonPremiumJoinMessageRecord value1(java.lang.String value) {
		setMessage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NonPremiumJoinMessageRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NonPremiumJoinMessageRecord
	 */
	public NonPremiumJoinMessageRecord() {
		super(mineplex.database.tables.NonPremiumJoinMessage.nonPremiumJoinMessage);
	}

	/**
	 * Create a detached, initialised NonPremiumJoinMessageRecord
	 */
	public NonPremiumJoinMessageRecord(java.lang.String message) {
		super(mineplex.database.tables.NonPremiumJoinMessage.nonPremiumJoinMessage);

		setValue(0, message);
	}
}
