/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TitanGiveawayRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.TitanGiveawayRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record4<java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 619415176;

	/**
	 * Setter for <code>Account.titanGiveaway.accountId</code>.
	 */
	public void setAccountId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.titanGiveaway.accountId</code>.
	 */
	public java.lang.Integer getAccountId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.titanGiveaway.region</code>.
	 */
	public void setRegion(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.titanGiveaway.region</code>.
	 */
	public java.lang.String getRegion() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Account.titanGiveaway.time</code>.
	 */
	public void setTime(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.titanGiveaway.time</code>.
	 */
	public java.sql.Timestamp getTime() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>Account.titanGiveaway.serverName</code>.
	 */
	public void setServerName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.titanGiveaway.serverName</code>.
	 */
	public java.lang.String getServerName() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.TitanGiveaway.titanGiveaway.accountId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return mineplex.database.tables.TitanGiveaway.titanGiveaway.region;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return mineplex.database.tables.TitanGiveaway.titanGiveaway.time;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return mineplex.database.tables.TitanGiveaway.titanGiveaway.serverName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getRegion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getServerName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TitanGiveawayRecord value1(java.lang.Integer value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TitanGiveawayRecord value2(java.lang.String value) {
		setRegion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TitanGiveawayRecord value3(java.sql.Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TitanGiveawayRecord value4(java.lang.String value) {
		setServerName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TitanGiveawayRecord values(java.lang.Integer value1, java.lang.String value2, java.sql.Timestamp value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TitanGiveawayRecord
	 */
	public TitanGiveawayRecord() {
		super(mineplex.database.tables.TitanGiveaway.titanGiveaway);
	}

	/**
	 * Create a detached, initialised TitanGiveawayRecord
	 */
	public TitanGiveawayRecord(java.lang.Integer accountId, java.lang.String region, java.sql.Timestamp time, java.lang.String serverName) {
		super(mineplex.database.tables.TitanGiveaway.titanGiveaway);

		setValue(0, accountId);
		setValue(1, region);
		setValue(2, time);
		setValue(3, serverName);
	}
}
