/**
 * This class is generated by jOOQ
 */
package mineplex.database.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountGoldChange extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 360483639;

	/**
	 * The parameter <code>Account.accountGoldChange.accountId</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> accountId = createParameter("accountId", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.accountGoldChange.goldChange</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> goldChange = createParameter("goldChange", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.accountGoldChange.success</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Byte> success = createParameter("success", org.jooq.impl.SQLDataType.TINYINT, false);

	/**
	 * Create a new routine call instance
	 */
	public AccountGoldChange() {
		super("accountGoldChange", mineplex.database.Account.Account);

		addInParameter(accountId);
		addInParameter(goldChange);
		addOutParameter(success);
	}

	/**
	 * Set the <code>accountId</code> parameter IN value to the routine
	 */
	public void setAccountId(java.lang.Integer value) {
		setValue(mineplex.database.routines.AccountGoldChange.accountId, value);
	}

	/**
	 * Set the <code>goldChange</code> parameter IN value to the routine
	 */
	public void setGoldChange(java.lang.Integer value) {
		setValue(mineplex.database.routines.AccountGoldChange.goldChange, value);
	}

	/**
	 * Get the <code>success</code> parameter OUT value from the routine
	 */
	public java.lang.Byte getSuccess() {
		return getValue(success);
	}
}
