/**
 * This class is generated by jOOQ
 */
package mineplex.database.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddTip extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 2072534961;

	/**
	 * The parameter <code>Account.addTip.tipperAccountId</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> tipperAccountId = createParameter("tipperAccountId", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.addTip.boosterAccountId</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> boosterAccountId = createParameter("boosterAccountId", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.addTip.boosterId</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> boosterId = createParameter("boosterId", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.addTip.tipAmount</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> tipAmount = createParameter("tipAmount", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.addTip.success</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Byte> success = createParameter("success", org.jooq.impl.SQLDataType.TINYINT, false);

	/**
	 * Create a new routine call instance
	 */
	public AddTip() {
		super("addTip", mineplex.database.Account.Account);

		addInParameter(tipperAccountId);
		addInParameter(boosterAccountId);
		addInParameter(boosterId);
		addInParameter(tipAmount);
		addOutParameter(success);
	}

	/**
	 * Set the <code>tipperAccountId</code> parameter IN value to the routine
	 */
	public void setTipperAccountId(java.lang.Integer value) {
		setValue(mineplex.database.routines.AddTip.tipperAccountId, value);
	}

	/**
	 * Set the <code>boosterAccountId</code> parameter IN value to the routine
	 */
	public void setBoosterAccountId(java.lang.Integer value) {
		setValue(mineplex.database.routines.AddTip.boosterAccountId, value);
	}

	/**
	 * Set the <code>boosterId</code> parameter IN value to the routine
	 */
	public void setBoosterId(java.lang.Integer value) {
		setValue(mineplex.database.routines.AddTip.boosterId, value);
	}

	/**
	 * Set the <code>tipAmount</code> parameter IN value to the routine
	 */
	public void setTipAmount(java.lang.Integer value) {
		setValue(mineplex.database.routines.AddTip.tipAmount, value);
	}

	/**
	 * Get the <code>success</code> parameter OUT value from the routine
	 */
	public java.lang.Byte getSuccess() {
		return getValue(success);
	}
}
