/**
 * This class is generated by jOOQ
 */
package mineplex.database.routines;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClaimTips extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1769926553;

	/**
	 * The parameter <code>Account.claimTips.accountId_in</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> accountId_in = createParameter("accountId_in", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.claimTips.tipsClaimed</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> tipsClaimed = createParameter("tipsClaimed", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public ClaimTips() {
		super("claimTips", mineplex.database.Account.Account);

		addInParameter(accountId_in);
		addOutParameter(tipsClaimed);
	}

	/**
	 * Set the <code>accountId_in</code> parameter IN value to the routine
	 */
	public void setAccountId_in(java.lang.Integer value) {
		setValue(mineplex.database.routines.ClaimTips.accountId_in, value);
	}

	/**
	 * Get the <code>tipsClaimed</code> parameter OUT value from the routine
	 */
	public java.lang.Integer getTipsClaimed() {
		return getValue(tipsClaimed);
	}
}
