/**
 * This class is generated by jOOQ
 */
package mineplex.database.routines;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RankBonus extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 467761905;

	/**
	 * The parameter <code>Account.rankBonus.accountId_in</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> accountId_in = createParameter("accountId_in", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.rankBonus.coinsChange</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> coinsChange = createParameter("coinsChange", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.rankBonus.gemsChange</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> gemsChange = createParameter("gemsChange", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.rankBonus.mythicalChestChange</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> mythicalChestChange = createParameter("mythicalChestChange", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>Account.rankBonus.pass</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Byte> pass = createParameter("pass", org.jooq.impl.SQLDataType.TINYINT, false);

	/**
	 * The parameter <code>Account.rankBonus.outTime</code>.
	 */
	public static final org.jooq.Parameter<java.sql.Date> outTime = createParameter("outTime", org.jooq.impl.SQLDataType.DATE, false);

	/**
	 * Create a new routine call instance
	 */
	public RankBonus() {
		super("rankBonus", mineplex.database.Account.Account);

		addInParameter(accountId_in);
		addInParameter(coinsChange);
		addInParameter(gemsChange);
		addInParameter(mythicalChestChange);
		addOutParameter(pass);
		addOutParameter(outTime);
	}

	/**
	 * Set the <code>accountId_in</code> parameter IN value to the routine
	 */
	public void setAccountId_in(java.lang.Integer value) {
		setValue(mineplex.database.routines.RankBonus.accountId_in, value);
	}

	/**
	 * Set the <code>coinsChange</code> parameter IN value to the routine
	 */
	public void setCoinsChange(java.lang.Integer value) {
		setValue(mineplex.database.routines.RankBonus.coinsChange, value);
	}

	/**
	 * Set the <code>gemsChange</code> parameter IN value to the routine
	 */
	public void setGemsChange(java.lang.Integer value) {
		setValue(mineplex.database.routines.RankBonus.gemsChange, value);
	}

	/**
	 * Set the <code>mythicalChestChange</code> parameter IN value to the routine
	 */
	public void setMythicalChestChange(java.lang.Integer value) {
		setValue(mineplex.database.routines.RankBonus.mythicalChestChange, value);
	}

	/**
	 * Get the <code>pass</code> parameter OUT value from the routine
	 */
	public java.lang.Byte getPass() {
		return getValue(pass);
	}

	/**
	 * Get the <code>outTime</code> parameter OUT value from the routine
	 */
	public java.sql.Date getOutTime() {
		return getValue(outTime);
	}
}
