/**
 * This class is generated by jOOQ
 */
package mineplex.database.routines;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1143436751;

	/**
	 * The parameter <code>Account.test.playerUuid</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> playerUuid = createParameter("playerUuid", org.jooq.impl.SQLDataType.VARCHAR.length(100), false);

	/**
	 * The parameter <code>Account.test.playerName</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> playerName = createParameter("playerName", org.jooq.impl.SQLDataType.VARCHAR.length(100), false);

	/**
	 * Create a new routine call instance
	 */
	public Test() {
		super("test", mineplex.database.Account.Account);

		addInParameter(playerUuid);
		addInParameter(playerName);
	}

	/**
	 * Set the <code>playerUuid</code> parameter IN value to the routine
	 */
	public void setPlayerUuid(java.lang.String value) {
		setValue(mineplex.database.routines.Test.playerUuid, value);
	}

	/**
	 * Set the <code>playerName</code> parameter IN value to the routine
	 */
	public void setPlayerName(java.lang.String value) {
		setValue(mineplex.database.routines.Test.playerName, value);
	}
}
