/**
 * This class is generated by jOOQ
 */
package mineplex.database.routines;

/**
 * Update the leaderboard for all currently active tournaments.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdateTournaments extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 176108358;

	/**
	 * Create a new routine call instance
	 */
	public UpdateTournaments() {
		super("updateTournaments", mineplex.database.Account.Account);
	}
}
