/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountGiveaway extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountGiveawayRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -789027180;

	/**
	 * The reference instance of <code>Account.accountGiveaway</code>
	 */
	public static final mineplex.database.tables.AccountGiveaway accountGiveaway = new mineplex.database.tables.AccountGiveaway();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountGiveawayRecord> getRecordType() {
		return mineplex.database.tables.records.AccountGiveawayRecord.class;
	}

	/**
	 * The column <code>Account.accountGiveaway.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountGiveaway.giveawayId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.Integer> giveawayId = createField("giveawayId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountGiveaway.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountGiveaway.cooldownId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.Integer> cooldownId = createField("cooldownId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountGiveaway.region</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.String> region = createField("region", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>Account.accountGiveaway.serverName</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.String> serverName = createField("serverName", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>Account.accountGiveaway.time</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.sql.Timestamp> time = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.accountGiveaway.uuid</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.String> uuid = createField("uuid", org.jooq.impl.SQLDataType.CHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>Account.accountGiveaway.claimed</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.Byte> claimed = createField("claimed", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountGiveaway</code> table reference
	 */
	public AccountGiveaway() {
		this("accountGiveaway", null);
	}

	/**
	 * Create an aliased <code>Account.accountGiveaway</code> table reference
	 */
	public AccountGiveaway(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountGiveaway.accountGiveaway);
	}

	private AccountGiveaway(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountGiveawayRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountGiveaway(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountGiveawayRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.AccountGiveawayRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_accountGiveaway;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountGiveawayRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountGiveaway_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountGiveawayRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountGiveawayRecord>>asList(mineplex.database.Keys.KEY_accountGiveaway_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountGiveawayRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountGiveawayRecord, ?>>asList(mineplex.database.Keys.accountGiveaway_giveaway_id_fk, mineplex.database.Keys.accountGiveaway_accounts_id_fk, mineplex.database.Keys.accountGiveaway_giveawayCooldown_id_fk);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountGiveaway as(java.lang.String alias) {
		return new mineplex.database.tables.AccountGiveaway(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountGiveaway rename(java.lang.String name) {
		return new mineplex.database.tables.AccountGiveaway(name, null);
	}
}
