/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTipClaimLogs extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountTipClaimLogsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1872367416;

	/**
	 * The reference instance of <code>Account.accountTipClaimLogs</code>
	 */
	public static final mineplex.database.tables.AccountTipClaimLogs accountTipClaimLogs = new mineplex.database.tables.AccountTipClaimLogs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountTipClaimLogsRecord> getRecordType() {
		return mineplex.database.tables.records.AccountTipClaimLogsRecord.class;
	}

	/**
	 * The column <code>Account.accountTipClaimLogs.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipClaimLogsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTipClaimLogs.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipClaimLogsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTipClaimLogs.tipsClaimed</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipClaimLogsRecord, java.lang.Integer> tipsClaimed = createField("tipsClaimed", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTipClaimLogs.date</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipClaimLogsRecord, java.sql.Timestamp> date = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountTipClaimLogs</code> table reference
	 */
	public AccountTipClaimLogs() {
		this("accountTipClaimLogs", null);
	}

	/**
	 * Create an aliased <code>Account.accountTipClaimLogs</code> table reference
	 */
	public AccountTipClaimLogs(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountTipClaimLogs.accountTipClaimLogs);
	}

	private AccountTipClaimLogs(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountTipClaimLogsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountTipClaimLogs(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountTipClaimLogsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.AccountTipClaimLogsRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_accountTipClaimLogs;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipClaimLogsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountTipClaimLogs_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipClaimLogsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipClaimLogsRecord>>asList(mineplex.database.Keys.KEY_accountTipClaimLogs_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountTipClaimLogsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountTipClaimLogsRecord, ?>>asList(mineplex.database.Keys.accountTipClaimLogs_accounts_id_fk);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountTipClaimLogs as(java.lang.String alias) {
		return new mineplex.database.tables.AccountTipClaimLogs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountTipClaimLogs rename(java.lang.String name) {
		return new mineplex.database.tables.AccountTipClaimLogs(name, null);
	}
}
