/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTipLogs extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountTipLogsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1738208914;

	/**
	 * The reference instance of <code>Account.accountTipLogs</code>
	 */
	public static final mineplex.database.tables.AccountTipLogs accountTipLogs = new mineplex.database.tables.AccountTipLogs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountTipLogsRecord> getRecordType() {
		return mineplex.database.tables.records.AccountTipLogsRecord.class;
	}

	/**
	 * The column <code>Account.accountTipLogs.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipLogsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTipLogs.boosterId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipLogsRecord, java.lang.Integer> boosterId = createField("boosterId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTipLogs.date</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipLogsRecord, java.sql.Timestamp> date = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountTipLogs</code> table reference
	 */
	public AccountTipLogs() {
		this("accountTipLogs", null);
	}

	/**
	 * Create an aliased <code>Account.accountTipLogs</code> table reference
	 */
	public AccountTipLogs(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountTipLogs.accountTipLogs);
	}

	private AccountTipLogs(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountTipLogsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountTipLogs(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountTipLogsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipLogsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountTipLogs_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipLogsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipLogsRecord>>asList(mineplex.database.Keys.KEY_accountTipLogs_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountTipLogsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountTipLogsRecord, ?>>asList(mineplex.database.Keys.accountTipLogs_accounts_id_fk);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountTipLogs as(java.lang.String alias) {
		return new mineplex.database.tables.AccountTipLogs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountTipLogs rename(java.lang.String name) {
		return new mineplex.database.tables.AccountTipLogs(name, null);
	}
}
