/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountClan extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountClanRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 2122039221;

	/**
	 * The reference instance of <code>Account.accountClan</code>
	 */
	public static final mineplex.database.tables.AccountClan accountClan = new mineplex.database.tables.AccountClan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountClanRecord> getRecordType() {
		return mineplex.database.tables.records.AccountClanRecord.class;
	}

	/**
	 * The column <code>Account.accountClan.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountClanRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountClanRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.clanId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountClanRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.clanRole</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountClanRecord, java.lang.String> clanRole = createField("clanRole", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>Account.accountClan</code> table reference
	 */
	public AccountClan() {
		this("accountClan", null);
	}

	/**
	 * Create an aliased <code>Account.accountClan</code> table reference
	 */
	public AccountClan(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountClan.accountClan);
	}

	private AccountClan(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountClanRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountClan(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountClanRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.AccountClanRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_accountClan;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountClanRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountClan_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountClanRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountClanRecord>>asList(mineplex.database.Keys.KEY_accountClan_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountClan as(java.lang.String alias) {
		return new mineplex.database.tables.AccountClan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountClan rename(java.lang.String name) {
		return new mineplex.database.tables.AccountClan(name, null);
	}
}
