/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTip extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountTipRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1341675958;

	/**
	 * The reference instance of <code>Account.accountTip</code>
	 */
	public static final mineplex.database.tables.AccountTip accountTip = new mineplex.database.tables.AccountTip();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountTipRecord> getRecordType() {
		return mineplex.database.tables.records.AccountTipRecord.class;
	}

	/**
	 * The column <code>Account.accountTip.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTip.tips</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountTipRecord, java.lang.Integer> tips = createField("tips", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountTip</code> table reference
	 */
	public AccountTip() {
		this("accountTip", null);
	}

	/**
	 * Create an aliased <code>Account.accountTip</code> table reference
	 */
	public AccountTip(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountTip.accountTip);
	}

	private AccountTip(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountTipRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountTip(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountTipRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountTip_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountTipRecord>>asList(mineplex.database.Keys.KEY_accountTip_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountTipRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountTipRecord, ?>>asList(mineplex.database.Keys.accountTips_accounts_id_fk);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountTip as(java.lang.String alias) {
		return new mineplex.database.tables.AccountTip(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountTip rename(java.lang.String name) {
		return new mineplex.database.tables.AccountTip(name, null);
	}
}
