/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountPolls extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountPollsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1903716407;

	/**
	 * The reference instance of <code>Account.accountPolls</code>
	 */
	public static final mineplex.database.tables.AccountPolls accountPolls = new mineplex.database.tables.AccountPolls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountPollsRecord> getRecordType() {
		return mineplex.database.tables.records.AccountPollsRecord.class;
	}

	/**
	 * The column <code>Account.accountPolls.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPollsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPolls.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPollsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPolls.pollId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPollsRecord, java.lang.Integer> pollId = createField("pollId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPolls.value</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPollsRecord, java.lang.Byte> value = createField("value", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountPolls</code> table reference
	 */
	public AccountPolls() {
		this("accountPolls", null);
	}

	/**
	 * Create an aliased <code>Account.accountPolls</code> table reference
	 */
	public AccountPolls(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountPolls.accountPolls);
	}

	private AccountPolls(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountPollsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountPolls(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountPollsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.AccountPollsRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_accountPolls;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountPolls_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord>>asList(mineplex.database.Keys.KEY_accountPolls_PRIMARY, mineplex.database.Keys.KEY_accountPolls_accountPollIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountPollsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountPollsRecord, ?>>asList(mineplex.database.Keys.accountPolls_ibfk_1, mineplex.database.Keys.accountPolls_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountPolls as(java.lang.String alias) {
		return new mineplex.database.tables.AccountPolls(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountPolls rename(java.lang.String name) {
		return new mineplex.database.tables.AccountPolls(name, null);
	}
}
