/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountAmplifierThank extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountAmplifierThankRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -810649551;

	/**
	 * The reference instance of <code>Account.accountAmplifierThank</code>
	 */
	public static final mineplex.database.tables.AccountAmplifierThank accountAmplifierThank = new mineplex.database.tables.AccountAmplifierThank();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountAmplifierThankRecord> getRecordType() {
		return mineplex.database.tables.records.AccountAmplifierThankRecord.class;
	}

	/**
	 * The column <code>Account.accountAmplifierThank.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountAmplifierThankRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountAmplifierThank.amplifierId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountAmplifierThankRecord, java.lang.Integer> amplifierId = createField("amplifierId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountAmplifierThank.time</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountAmplifierThankRecord, java.sql.Timestamp> time = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountAmplifierThank</code> table reference
	 */
	public AccountAmplifierThank() {
		this("accountAmplifierThank", null);
	}

	/**
	 * Create an aliased <code>Account.accountAmplifierThank</code> table reference
	 */
	public AccountAmplifierThank(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountAmplifierThank.accountAmplifierThank);
	}

	private AccountAmplifierThank(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountAmplifierThankRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountAmplifierThank(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountAmplifierThankRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountAmplifierThankRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountAmplifierThank_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountAmplifierThankRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountAmplifierThankRecord>>asList(mineplex.database.Keys.KEY_accountAmplifierThank_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountAmplifierThankRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountAmplifierThankRecord, ?>>asList(mineplex.database.Keys.accountAmplifierThank_accounts_id_fk);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountAmplifierThank as(java.lang.String alias) {
		return new mineplex.database.tables.AccountAmplifierThank(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountAmplifierThank rename(java.lang.String name) {
		return new mineplex.database.tables.AccountAmplifierThank(name, null);
	}
}
