/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountPurchases extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountPurchasesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 787682446;

	/**
	 * The reference instance of <code>Account.accountPurchases</code>
	 */
	public static final mineplex.database.tables.AccountPurchases accountPurchases = new mineplex.database.tables.AccountPurchases();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountPurchasesRecord> getRecordType() {
		return mineplex.database.tables.records.AccountPurchasesRecord.class;
	}

	/**
	 * The column <code>Account.accountPurchases.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPurchasesRecord, java.lang.Long> id = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPurchases.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPurchasesRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPurchases.packageId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPurchasesRecord, java.lang.Integer> packageId = createField("packageId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPurchases.amount</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPurchasesRecord, java.lang.Integer> amount = createField("amount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPurchases.date</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPurchasesRecord, java.sql.Timestamp> date = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.accountPurchases.success</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountPurchasesRecord, java.lang.Byte> success = createField("success", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountPurchases</code> table reference
	 */
	public AccountPurchases() {
		this("accountPurchases", null);
	}

	/**
	 * Create an aliased <code>Account.accountPurchases</code> table reference
	 */
	public AccountPurchases(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountPurchases.accountPurchases);
	}

	private AccountPurchases(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountPurchasesRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountPurchases(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountPurchasesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.AccountPurchasesRecord, java.lang.Long> getIdentity() {
		return mineplex.database.Keys.IDENTITY_accountPurchases;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountPurchasesRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountPurchases_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountPurchasesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountPurchasesRecord>>asList(mineplex.database.Keys.KEY_accountPurchases_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountPurchasesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountPurchasesRecord, ?>>asList(mineplex.database.Keys.ACCOUNT_PURCHASE_ID, mineplex.database.Keys.PACKAGENAME_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountPurchases as(java.lang.String alias) {
		return new mineplex.database.tables.AccountPurchases(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountPurchases rename(java.lang.String name) {
		return new mineplex.database.tables.AccountPurchases(name, null);
	}
}
