/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountValentinesGift extends org.jooq.impl.TableImpl<mineplex.database.tables.records.AccountValentinesGiftRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -654747312;

	/**
	 * The reference instance of <code>Account.accountValentinesGift</code>
	 */
	public static final mineplex.database.tables.AccountValentinesGift accountValentinesGift = new mineplex.database.tables.AccountValentinesGift();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.AccountValentinesGiftRecord> getRecordType() {
		return mineplex.database.tables.records.AccountValentinesGiftRecord.class;
	}

	/**
	 * The column <code>Account.accountValentinesGift.senderId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountValentinesGiftRecord, java.lang.Integer> senderId = createField("senderId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountValentinesGift.targetId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountValentinesGiftRecord, java.lang.Integer> targetId = createField("targetId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountValentinesGift.time</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.AccountValentinesGiftRecord, java.sql.Timestamp> time = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountValentinesGift</code> table reference
	 */
	public AccountValentinesGift() {
		this("accountValentinesGift", null);
	}

	/**
	 * Create an aliased <code>Account.accountValentinesGift</code> table reference
	 */
	public AccountValentinesGift(java.lang.String alias) {
		this(alias, mineplex.database.tables.AccountValentinesGift.accountValentinesGift);
	}

	private AccountValentinesGift(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountValentinesGiftRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountValentinesGift(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.AccountValentinesGiftRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.AccountValentinesGiftRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_accountValentinesGift_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.AccountValentinesGiftRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.AccountValentinesGiftRecord>>asList(mineplex.database.Keys.KEY_accountValentinesGift_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.AccountValentinesGiftRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.AccountValentinesGiftRecord, ?>>asList(mineplex.database.Keys.accountValentines_sender_fk, mineplex.database.Keys.accountValentines_target_fk);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.AccountValentinesGift as(java.lang.String alias) {
		return new mineplex.database.tables.AccountValentinesGift(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.AccountValentinesGift rename(java.lang.String name) {
		return new mineplex.database.tables.AccountValentinesGift(name, null);
	}
}
