/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chatsnap extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ChatsnapRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -176946707;

	/**
	 * The reference instance of <code>Account.chatsnap</code>
	 */
	public static final mineplex.database.tables.Chatsnap chatsnap = new mineplex.database.tables.Chatsnap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ChatsnapRecord> getRecordType() {
		return mineplex.database.tables.records.ChatsnapRecord.class;
	}

	/**
	 * The column <code>Account.chatsnap.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.chatsnap.reporterId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.lang.Integer> reporterId = createField("reporterId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.chatsnap.reporteeId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.lang.Integer> reporteeId = createField("reporteeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.chatsnap.time</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.sql.Timestamp> time = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.chatsnap.status</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.lang.String> status = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.chatsnap.reason</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.lang.String> reason = createField("reason", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>Account.chatsnap.data</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ChatsnapRecord, java.lang.String> data = createField("data", org.jooq.impl.SQLDataType.CLOB.length(16777215).nullable(false), this, "");

	/**
	 * Create a <code>Account.chatsnap</code> table reference
	 */
	public Chatsnap() {
		this("chatsnap", null);
	}

	/**
	 * Create an aliased <code>Account.chatsnap</code> table reference
	 */
	public Chatsnap(java.lang.String alias) {
		this(alias, mineplex.database.tables.Chatsnap.chatsnap);
	}

	private Chatsnap(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ChatsnapRecord> aliased) {
		this(alias, aliased, null);
	}

	private Chatsnap(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ChatsnapRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.ChatsnapRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_chatsnap;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ChatsnapRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_chatsnap_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ChatsnapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ChatsnapRecord>>asList(mineplex.database.Keys.KEY_chatsnap_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.Chatsnap as(java.lang.String alias) {
		return new mineplex.database.tables.Chatsnap(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.Chatsnap rename(java.lang.String name) {
		return new mineplex.database.tables.Chatsnap(name, null);
	}
}
