/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansGold extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ClansGoldRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 950104617;

	/**
	 * The reference instance of <code>Account.clansGold</code>
	 */
	public static final mineplex.database.tables.ClansGold clansGold = new mineplex.database.tables.ClansGold();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ClansGoldRecord> getRecordType() {
		return mineplex.database.tables.records.ClansGoldRecord.class;
	}

	/**
	 * The column <code>Account.clansGold.serverId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansGoldRecord, java.lang.Integer> serverId = createField("serverId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clansGold.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansGoldRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clansGold.gold</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansGoldRecord, java.lang.Integer> gold = createField("gold", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.clansGold</code> table reference
	 */
	public ClansGold() {
		this("clansGold", null);
	}

	/**
	 * Create an aliased <code>Account.clansGold</code> table reference
	 */
	public ClansGold(java.lang.String alias) {
		this(alias, mineplex.database.tables.ClansGold.clansGold);
	}

	private ClansGold(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClansGoldRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClansGold(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClansGoldRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ClansGoldRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_clansGold_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ClansGoldRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ClansGoldRecord>>asList(mineplex.database.Keys.KEY_clansGold_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.ClansGoldRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.ClansGoldRecord, ?>>asList(mineplex.database.Keys.clansGold_ibfk_1, mineplex.database.Keys.clansGold_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.ClansGold as(java.lang.String alias) {
		return new mineplex.database.tables.ClansGold(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.ClansGold rename(java.lang.String name) {
		return new mineplex.database.tables.ClansGold(name, null);
	}
}
