/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansNetherPortals extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ClansNetherPortalsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1556693012;

	/**
	 * The reference instance of <code>Account.clansNetherPortals</code>
	 */
	public static final mineplex.database.tables.ClansNetherPortals clansNetherPortals = new mineplex.database.tables.ClansNetherPortals();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ClansNetherPortalsRecord> getRecordType() {
		return mineplex.database.tables.records.ClansNetherPortalsRecord.class;
	}

	/**
	 * The column <code>Account.clansNetherPortals.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansNetherPortalsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clansNetherPortals.cornerOne</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansNetherPortalsRecord, java.lang.String> cornerOne = createField("cornerOne", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>Account.clansNetherPortals.cornerTwo</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansNetherPortalsRecord, java.lang.String> cornerTwo = createField("cornerTwo", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>Account.clansNetherPortals.returnPortal</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansNetherPortalsRecord, java.lang.Byte> returnPortal = createField("returnPortal", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * Create a <code>Account.clansNetherPortals</code> table reference
	 */
	public ClansNetherPortals() {
		this("clansNetherPortals", null);
	}

	/**
	 * Create an aliased <code>Account.clansNetherPortals</code> table reference
	 */
	public ClansNetherPortals(java.lang.String alias) {
		this(alias, mineplex.database.tables.ClansNetherPortals.clansNetherPortals);
	}

	private ClansNetherPortals(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClansNetherPortalsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClansNetherPortals(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClansNetherPortalsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.ClansNetherPortalsRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_clansNetherPortals;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ClansNetherPortalsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_clansNetherPortals_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ClansNetherPortalsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ClansNetherPortalsRecord>>asList(mineplex.database.Keys.KEY_clansNetherPortals_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.ClansNetherPortals as(java.lang.String alias) {
		return new mineplex.database.tables.ClansNetherPortals(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.ClansNetherPortals rename(java.lang.String name) {
		return new mineplex.database.tables.ClansNetherPortals(name, null);
	}
}
