/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanWar extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ClanWarRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1997659837;

	/**
	 * The reference instance of <code>Account.clanWar</code>
	 */
	public static final mineplex.database.tables.ClanWar clanWar = new mineplex.database.tables.ClanWar();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ClanWarRecord> getRecordType() {
		return mineplex.database.tables.records.ClanWarRecord.class;
	}

	/**
	 * The column <code>Account.clanWar.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanWar.initiatorId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.lang.Integer> initiatorId = createField("initiatorId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanWar.clanId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanWar.score</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.lang.Integer> score = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanWar.completed</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.lang.Byte> completed = createField("completed", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>Account.clanWar.created</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.sql.Timestamp> created = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.clanWar.ended</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.sql.Timestamp> ended = createField("ended", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>Account.clanWar.lastUpdated</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClanWarRecord, java.sql.Timestamp> lastUpdated = createField("lastUpdated", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.clanWar</code> table reference
	 */
	public ClanWar() {
		this("clanWar", null);
	}

	/**
	 * Create an aliased <code>Account.clanWar</code> table reference
	 */
	public ClanWar(java.lang.String alias) {
		this(alias, mineplex.database.tables.ClanWar.clanWar);
	}

	private ClanWar(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClanWarRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanWar(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClanWarRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.ClanWarRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_clanWar;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ClanWarRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_clanWar_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ClanWarRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ClanWarRecord>>asList(mineplex.database.Keys.KEY_clanWar_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.ClanWar as(java.lang.String alias) {
		return new mineplex.database.tables.ClanWar(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.ClanWar rename(java.lang.String name) {
		return new mineplex.database.tables.ClanWar(name, null);
	}
}
