/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansOutposts extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ClansOutpostsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1523741969;

	/**
	 * The reference instance of <code>Account.clansOutposts</code>
	 */
	public static final mineplex.database.tables.ClansOutposts clansOutposts = new mineplex.database.tables.ClansOutposts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ClansOutpostsRecord> getRecordType() {
		return mineplex.database.tables.records.ClansOutpostsRecord.class;
	}

	/**
	 * The column <code>Account.clansOutposts.uniqueId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.Integer> uniqueId = createField("uniqueId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clansOutposts.serverId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.Integer> serverId = createField("serverId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clansOutposts.origin</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.String> origin = createField("origin", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>Account.clansOutposts.outpostType</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.Byte> outpostType = createField("outpostType", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>Account.clansOutposts.ownerClan</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.Integer> ownerClan = createField("ownerClan", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clansOutposts.timeSpawned</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.String> timeSpawned = createField("timeSpawned", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * The column <code>Account.clansOutposts.outpostState</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ClansOutpostsRecord, java.lang.Byte> outpostState = createField("outpostState", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>Account.clansOutposts</code> table reference
	 */
	public ClansOutposts() {
		this("clansOutposts", null);
	}

	/**
	 * Create an aliased <code>Account.clansOutposts</code> table reference
	 */
	public ClansOutposts(java.lang.String alias) {
		this(alias, mineplex.database.tables.ClansOutposts.clansOutposts);
	}

	private ClansOutposts(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClansOutpostsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClansOutposts(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ClansOutpostsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ClansOutpostsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_clansOutposts_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ClansOutpostsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ClansOutpostsRecord>>asList(mineplex.database.Keys.KEY_clansOutposts_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.ClansOutposts as(java.lang.String alias) {
		return new mineplex.database.tables.ClansOutposts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.ClansOutposts rename(java.lang.String name) {
		return new mineplex.database.tables.ClansOutposts(name, null);
	}
}
