/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomData extends org.jooq.impl.TableImpl<mineplex.database.tables.records.CustomDataRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -220428349;

	/**
	 * The reference instance of <code>Account.customData</code>
	 */
	public static final mineplex.database.tables.CustomData customData = new mineplex.database.tables.CustomData();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.CustomDataRecord> getRecordType() {
		return mineplex.database.tables.records.CustomDataRecord.class;
	}

	/**
	 * The column <code>Account.customData.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.CustomDataRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.customData.name</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.CustomDataRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>Account.customData</code> table reference
	 */
	public CustomData() {
		this("customData", null);
	}

	/**
	 * Create an aliased <code>Account.customData</code> table reference
	 */
	public CustomData(java.lang.String alias) {
		this(alias, mineplex.database.tables.CustomData.customData);
	}

	private CustomData(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.CustomDataRecord> aliased) {
		this(alias, aliased, null);
	}

	private CustomData(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.CustomDataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.CustomDataRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_customData;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.CustomDataRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_customData_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.CustomDataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.CustomDataRecord>>asList(mineplex.database.Keys.KEY_customData_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.CustomData as(java.lang.String alias) {
		return new mineplex.database.tables.CustomData(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.CustomData rename(java.lang.String name) {
		return new mineplex.database.tables.CustomData(name, null);
	}
}
