/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Items extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ItemsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -2111929737;

	/**
	 * The reference instance of <code>Account.items</code>
	 */
	public static final mineplex.database.tables.Items items = new mineplex.database.tables.Items();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ItemsRecord> getRecordType() {
		return mineplex.database.tables.records.ItemsRecord.class;
	}

	/**
	 * The column <code>Account.items.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ItemsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.items.name</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ItemsRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.items.categoryId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ItemsRecord, java.lang.Integer> categoryId = createField("categoryId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.items.rarity</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ItemsRecord, java.lang.Integer> rarity = createField("rarity", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>Account.items</code> table reference
	 */
	public Items() {
		this("items", null);
	}

	/**
	 * Create an aliased <code>Account.items</code> table reference
	 */
	public Items(java.lang.String alias) {
		this(alias, mineplex.database.tables.Items.items);
	}

	private Items(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ItemsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Items(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ItemsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.ItemsRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_items;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_items_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord>>asList(mineplex.database.Keys.KEY_items_PRIMARY, mineplex.database.Keys.KEY_items_name_UNIQUE, mineplex.database.Keys.KEY_items_uniqueNameCategoryIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.Items as(java.lang.String alias) {
		return new mineplex.database.tables.Items(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.Items rename(java.lang.String name) {
		return new mineplex.database.tables.Items(name, null);
	}
}
