/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kitpreferences extends org.jooq.impl.TableImpl<mineplex.database.tables.records.KitpreferencesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -818455351;

	/**
	 * The reference instance of <code>Account.kitpreferences</code>
	 */
	public static final mineplex.database.tables.Kitpreferences kitpreferences = new mineplex.database.tables.Kitpreferences();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.KitpreferencesRecord> getRecordType() {
		return mineplex.database.tables.records.KitpreferencesRecord.class;
	}

	/**
	 * The column <code>Account.kitpreferences.accountid</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.KitpreferencesRecord, java.lang.Integer> accountid = createField("accountid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.kitpreferences.gameid</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.KitpreferencesRecord, java.lang.Integer> gameid = createField("gameid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.kitpreferences.kitid</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.KitpreferencesRecord, java.lang.Integer> kitid = createField("kitid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>Account.kitpreferences</code> table reference
	 */
	public Kitpreferences() {
		this("kitpreferences", null);
	}

	/**
	 * Create an aliased <code>Account.kitpreferences</code> table reference
	 */
	public Kitpreferences(java.lang.String alias) {
		this(alias, mineplex.database.tables.Kitpreferences.kitpreferences);
	}

	private Kitpreferences(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.KitpreferencesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Kitpreferences(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.KitpreferencesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.Kitpreferences as(java.lang.String alias) {
		return new mineplex.database.tables.Kitpreferences(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.Kitpreferences rename(java.lang.String name) {
		return new mineplex.database.tables.Kitpreferences(name, null);
	}
}
