/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NonPremiumJoinMessage extends org.jooq.impl.TableImpl<mineplex.database.tables.records.NonPremiumJoinMessageRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1100695916;

	/**
	 * The reference instance of <code>Account.nonPremiumJoinMessage</code>
	 */
	public static final mineplex.database.tables.NonPremiumJoinMessage nonPremiumJoinMessage = new mineplex.database.tables.NonPremiumJoinMessage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.NonPremiumJoinMessageRecord> getRecordType() {
		return mineplex.database.tables.records.NonPremiumJoinMessageRecord.class;
	}

	/**
	 * The column <code>Account.nonPremiumJoinMessage.message</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.NonPremiumJoinMessageRecord, java.lang.String> message = createField("message", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Account.nonPremiumJoinMessage</code> table reference
	 */
	public NonPremiumJoinMessage() {
		this("nonPremiumJoinMessage", null);
	}

	/**
	 * Create an aliased <code>Account.nonPremiumJoinMessage</code> table reference
	 */
	public NonPremiumJoinMessage(java.lang.String alias) {
		this(alias, mineplex.database.tables.NonPremiumJoinMessage.nonPremiumJoinMessage);
	}

	private NonPremiumJoinMessage(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.NonPremiumJoinMessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private NonPremiumJoinMessage(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.NonPremiumJoinMessageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.NonPremiumJoinMessage as(java.lang.String alias) {
		return new mineplex.database.tables.NonPremiumJoinMessage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.NonPremiumJoinMessage rename(java.lang.String name) {
		return new mineplex.database.tables.NonPremiumJoinMessage(name, null);
	}
}
