/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PowerPlayClub extends org.jooq.impl.TableImpl<mineplex.database.tables.records.PowerPlayClubRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -521671017;

	/**
	 * The reference instance of <code>Account.powerPlayClub</code>
	 */
	public static final mineplex.database.tables.PowerPlayClub powerPlayClub = new mineplex.database.tables.PowerPlayClub();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.PowerPlayClubRecord> getRecordType() {
		return mineplex.database.tables.records.PowerPlayClubRecord.class;
	}

	/**
	 * The column <code>Account.powerPlayClub.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.PowerPlayClubRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.powerPlayClub.kvKey</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.PowerPlayClubRecord, java.lang.String> kvKey = createField("kvKey", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>Account.powerPlayClub.kvValue</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.PowerPlayClubRecord, java.lang.Integer> kvValue = createField("kvValue", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.powerPlayClub</code> table reference
	 */
	public PowerPlayClub() {
		this("powerPlayClub", null);
	}

	/**
	 * Create an aliased <code>Account.powerPlayClub</code> table reference
	 */
	public PowerPlayClub(java.lang.String alias) {
		this(alias, mineplex.database.tables.PowerPlayClub.powerPlayClub);
	}

	private PowerPlayClub(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.PowerPlayClubRecord> aliased) {
		this(alias, aliased, null);
	}

	private PowerPlayClub(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.PowerPlayClubRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.PowerPlayClubRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_powerPlayClub_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.PowerPlayClubRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.PowerPlayClubRecord>>asList(mineplex.database.Keys.KEY_powerPlayClub_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.PowerPlayClubRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.PowerPlayClubRecord, ?>>asList(mineplex.database.Keys.powerPlayClub_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.PowerPlayClub as(java.lang.String alias) {
		return new mineplex.database.tables.PowerPlayClub(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.PowerPlayClub rename(java.lang.String name) {
		return new mineplex.database.tables.PowerPlayClub(name, null);
	}
}
