/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RankedBans extends org.jooq.impl.TableImpl<mineplex.database.tables.records.RankedBansRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1023809174;

	/**
	 * The reference instance of <code>Account.rankedBans</code>
	 */
	public static final mineplex.database.tables.RankedBans rankedBans = new mineplex.database.tables.RankedBans();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.RankedBansRecord> getRecordType() {
		return mineplex.database.tables.records.RankedBansRecord.class;
	}

	/**
	 * The column <code>Account.rankedBans.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.RankedBansRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.rankedBans.strikes</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.RankedBansRecord, java.lang.Integer> strikes = createField("strikes", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.rankedBans.strikesExpire</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.RankedBansRecord, java.lang.String> strikesExpire = createField("strikesExpire", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * The column <code>Account.rankedBans.banEnd</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.RankedBansRecord, java.lang.String> banEnd = createField("banEnd", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * Create a <code>Account.rankedBans</code> table reference
	 */
	public RankedBans() {
		this("rankedBans", null);
	}

	/**
	 * Create an aliased <code>Account.rankedBans</code> table reference
	 */
	public RankedBans(java.lang.String alias) {
		this(alias, mineplex.database.tables.RankedBans.rankedBans);
	}

	private RankedBans(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.RankedBansRecord> aliased) {
		this(alias, aliased, null);
	}

	private RankedBans(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.RankedBansRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.RankedBansRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_rankedBans_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.RankedBansRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.RankedBansRecord>>asList(mineplex.database.Keys.KEY_rankedBans_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.RankedBans as(java.lang.String alias) {
		return new mineplex.database.tables.RankedBans(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.RankedBans rename(java.lang.String name) {
		return new mineplex.database.tables.RankedBans(name, null);
	}
}
