/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportTickets extends org.jooq.impl.TableImpl<mineplex.database.tables.records.ReportTicketsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 778901082;

	/**
	 * The reference instance of <code>Account.reportTickets</code>
	 */
	public static final mineplex.database.tables.ReportTickets reportTickets = new mineplex.database.tables.ReportTickets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.ReportTicketsRecord> getRecordType() {
		return mineplex.database.tables.records.ReportTicketsRecord.class;
	}

	/**
	 * The column <code>Account.reportTickets.reportId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.Integer> reportId = createField("reportId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.reportTickets.date</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.String> date = createField("date", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * The column <code>Account.reportTickets.eventDate</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.String> eventDate = createField("eventDate", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * The column <code>Account.reportTickets.playerId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.Integer> playerId = createField("playerId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.reportTickets.server</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.String> server = createField("server", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>Account.reportTickets.closerId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.Integer> closerId = createField("closerId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.reportTickets.result</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.String> result = createField("result", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

	/**
	 * The column <code>Account.reportTickets.reason</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.ReportTicketsRecord, java.lang.String> reason = createField("reason", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.reportTickets</code> table reference
	 */
	public ReportTickets() {
		this("reportTickets", null);
	}

	/**
	 * Create an aliased <code>Account.reportTickets</code> table reference
	 */
	public ReportTickets(java.lang.String alias) {
		this(alias, mineplex.database.tables.ReportTickets.reportTickets);
	}

	private ReportTickets(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ReportTicketsRecord> aliased) {
		this(alias, aliased, null);
	}

	private ReportTickets(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.ReportTicketsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.ReportTicketsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_reportTickets_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.ReportTicketsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.ReportTicketsRecord>>asList(mineplex.database.Keys.KEY_reportTickets_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.ReportTickets as(java.lang.String alias) {
		return new mineplex.database.tables.ReportTickets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.ReportTickets rename(java.lang.String name) {
		return new mineplex.database.tables.ReportTickets(name, null);
	}
}
