/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Selectedmodifiers extends org.jooq.impl.TableImpl<mineplex.database.tables.records.SelectedmodifiersRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -215495432;

	/**
	 * The reference instance of <code>Account.selectedmodifiers</code>
	 */
	public static final mineplex.database.tables.Selectedmodifiers selectedmodifiers = new mineplex.database.tables.Selectedmodifiers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.SelectedmodifiersRecord> getRecordType() {
		return mineplex.database.tables.records.SelectedmodifiersRecord.class;
	}

	/**
	 * The column <code>Account.selectedmodifiers.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.SelectedmodifiersRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.selectedmodifiers.selected</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.SelectedmodifiersRecord, java.lang.String> selected = createField("selected", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * Create a <code>Account.selectedmodifiers</code> table reference
	 */
	public Selectedmodifiers() {
		this("selectedmodifiers", null);
	}

	/**
	 * Create an aliased <code>Account.selectedmodifiers</code> table reference
	 */
	public Selectedmodifiers(java.lang.String alias) {
		this(alias, mineplex.database.tables.Selectedmodifiers.selectedmodifiers);
	}

	private Selectedmodifiers(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.SelectedmodifiersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Selectedmodifiers(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.SelectedmodifiersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.Selectedmodifiers as(java.lang.String alias) {
		return new mineplex.database.tables.Selectedmodifiers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.Selectedmodifiers rename(java.lang.String name) {
		return new mineplex.database.tables.Selectedmodifiers(name, null);
	}
}
