/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TournamentTeams extends org.jooq.impl.TableImpl<mineplex.database.tables.records.TournamentTeamsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1573084229;

	/**
	 * The reference instance of <code>Account.tournamentTeams</code>
	 */
	public static final mineplex.database.tables.TournamentTeams tournamentTeams = new mineplex.database.tables.TournamentTeams();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.TournamentTeamsRecord> getRecordType() {
		return mineplex.database.tables.records.TournamentTeamsRecord.class;
	}

	/**
	 * The column <code>Account.tournamentTeams.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.TournamentTeamsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.tournamentTeams.tournamentId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.TournamentTeamsRecord, java.lang.Integer> tournamentId = createField("tournamentId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.tournamentTeams.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.TournamentTeamsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.tournamentTeams.status</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.TournamentTeamsRecord, java.lang.String> status = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(11), this, "");

	/**
	 * Create a <code>Account.tournamentTeams</code> table reference
	 */
	public TournamentTeams() {
		this("tournamentTeams", null);
	}

	/**
	 * Create an aliased <code>Account.tournamentTeams</code> table reference
	 */
	public TournamentTeams(java.lang.String alias) {
		this(alias, mineplex.database.tables.TournamentTeams.tournamentTeams);
	}

	private TournamentTeams(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.TournamentTeamsRecord> aliased) {
		this(alias, aliased, null);
	}

	private TournamentTeams(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.TournamentTeamsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.TournamentTeamsRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_tournamentTeams;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.TournamentTeamsRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_tournamentTeams_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.TournamentTeamsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.TournamentTeamsRecord>>asList(mineplex.database.Keys.KEY_tournamentTeams_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.TournamentTeamsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.TournamentTeamsRecord, ?>>asList(mineplex.database.Keys.TEAM_TOURNAMENT_KEY, mineplex.database.Keys.TEAM_TOURNAMENT_ACCOUNT_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.TournamentTeams as(java.lang.String alias) {
		return new mineplex.database.tables.TournamentTeams(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.TournamentTeams rename(java.lang.String name) {
		return new mineplex.database.tables.TournamentTeams(name, null);
	}
}
