/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Unicodereplacer extends org.jooq.impl.TableImpl<mineplex.database.tables.records.UnicodereplacerRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 613849358;

	/**
	 * The reference instance of <code>Account.unicodereplacer</code>
	 */
	public static final mineplex.database.tables.Unicodereplacer unicodereplacer = new mineplex.database.tables.Unicodereplacer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.UnicodereplacerRecord> getRecordType() {
		return mineplex.database.tables.records.UnicodereplacerRecord.class;
	}

	/**
	 * The column <code>Account.unicodereplacer.id</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.UnicodereplacerRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.unicodereplacer.unicode</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.UnicodereplacerRecord, java.lang.String> unicode = createField("unicode", org.jooq.impl.SQLDataType.VARCHAR.length(4), this, "");

	/**
	 * The column <code>Account.unicodereplacer.replacement</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.UnicodereplacerRecord, java.lang.String> replacement = createField("replacement", org.jooq.impl.SQLDataType.VARCHAR.length(8), this, "");

	/**
	 * The column <code>Account.unicodereplacer.created_by</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.UnicodereplacerRecord, java.lang.String> created_by = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>Account.unicodereplacer.removed_by</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.UnicodereplacerRecord, java.lang.String> removed_by = createField("removed_by", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * Create a <code>Account.unicodereplacer</code> table reference
	 */
	public Unicodereplacer() {
		this("unicodereplacer", null);
	}

	/**
	 * Create an aliased <code>Account.unicodereplacer</code> table reference
	 */
	public Unicodereplacer(java.lang.String alias) {
		this(alias, mineplex.database.tables.Unicodereplacer.unicodereplacer);
	}

	private Unicodereplacer(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.UnicodereplacerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Unicodereplacer(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.UnicodereplacerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.UnicodereplacerRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_unicodereplacer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.UnicodereplacerRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_unicodereplacer_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.UnicodereplacerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.UnicodereplacerRecord>>asList(mineplex.database.Keys.KEY_unicodereplacer_PRIMARY, mineplex.database.Keys.KEY_unicodereplacer_unicode);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.Unicodereplacer as(java.lang.String alias) {
		return new mineplex.database.tables.Unicodereplacer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.Unicodereplacer rename(java.lang.String name) {
		return new mineplex.database.tables.Unicodereplacer(name, null);
	}
}
