/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables;

/**
 * This class is generated by jOOQ.
 */

@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Youtube extends org.jooq.impl.TableImpl<mineplex.database.tables.records.YoutubeRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1588929727;

	/**
	 * The reference instance of <code>Account.youtube</code>
	 */
	public static final mineplex.database.tables.Youtube youtube = new mineplex.database.tables.Youtube();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<mineplex.database.tables.records.YoutubeRecord> getRecordType() {
		return mineplex.database.tables.records.YoutubeRecord.class;
	}

	/**
	 * The column <code>Account.youtube.accountId</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.YoutubeRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.youtube.clicktime</code>.
	 */
	public final org.jooq.TableField<mineplex.database.tables.records.YoutubeRecord, java.sql.Date> clicktime = createField("clicktime", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>Account.youtube</code> table reference
	 */
	public Youtube() {
		this("youtube", null);
	}

	/**
	 * Create an aliased <code>Account.youtube</code> table reference
	 */
	public Youtube(java.lang.String alias) {
		this(alias, mineplex.database.tables.Youtube.youtube);
	}

	private Youtube(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.YoutubeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Youtube(java.lang.String alias, org.jooq.Table<mineplex.database.tables.records.YoutubeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, mineplex.database.Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<mineplex.database.tables.records.YoutubeRecord, java.lang.Integer> getIdentity() {
		return mineplex.database.Keys.IDENTITY_youtube;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<mineplex.database.tables.records.YoutubeRecord> getPrimaryKey() {
		return mineplex.database.Keys.KEY_youtube_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<mineplex.database.tables.records.YoutubeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<mineplex.database.tables.records.YoutubeRecord>>asList(mineplex.database.Keys.KEY_youtube_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<mineplex.database.tables.records.YoutubeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<mineplex.database.tables.records.YoutubeRecord, ?>>asList(mineplex.database.Keys.youtube_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public mineplex.database.tables.Youtube as(java.lang.String alias) {
		return new mineplex.database.tables.Youtube(alias, this);
	}

	/**
	 * Rename this table
	 */
	public mineplex.database.tables.Youtube rename(java.lang.String name) {
		return new mineplex.database.tables.Youtube(name, null);
	}
}
