package mineplex.core.gadget.gadgets.flag;

import mineplex.core.common.util.banner.CountryFlag;
import mineplex.core.gadget.util.CostConstants;

/**
 * Cosmetic flags represented using banners.
 */
public enum FlagType
{

	MINEPLEX(CountryFlag.MINEPLEX, CostConstants.FOUND_IN_GINGERBREAD_CHESTS),
	RUDOLPH(CountryFlag.RUDOLPH, CostConstants.FOUND_IN_GINGERBREAD_CHESTS),
	CHRISTMAS_TREE(CountryFlag.CHRISTMAS_TREE, CostConstants.FOUND_IN_GINGERBREAD_CHESTS),
	PRESENT(CountryFlag.PRESENT, CostConstants.FOUND_IN_GINGERBREAD_CHESTS),
	WREATH(CountryFlag.WREATH, CostConstants.FOUND_IN_GINGERBREAD_CHESTS),
	SNOW_FLAKE(CountryFlag.SNOW_FLAKE, CostConstants.FOUND_IN_GINGERBREAD_CHESTS),
	HEART(CountryFlag.HEART, CostConstants.FOUND_IN_TREASURE_CHESTS),

	// Country
	AFGHANISTAN(CountryFlag.AFGHANISTAN, -1),
	ALBANIA(CountryFlag.ALBANIA, -1),
	ALGERIA(CountryFlag.ALGERIA, -1),
	ANGOLA(CountryFlag.ANGOLA, -1),
	ARGENTINA(CountryFlag.ARGENTINA, -1),
	ARMENIA(CountryFlag.ARMENIA, -1),
	AUSTRALIA(CountryFlag.AUSTRALIA, -1),
	AUSTRIA(CountryFlag.AUSTRIA, -1),
	AZERBAIJAN(CountryFlag.AZERBAIJAN, -1),
	BAHRAIN(CountryFlag.BAHRAIN, -1),
	BANGLADESH(CountryFlag.BANGLADESH, -1),
	BELARUS(CountryFlag.BELARUS, -1),
	BELGIUM(CountryFlag.BELGIUM, -1),
	BERMUDA(CountryFlag.BERMUDA, -1),
	BHUTAN(CountryFlag.BHUTAN, -1),
	BOLIVIA(CountryFlag.BOLIVIA, -1),
	BOSNIA_AND_HERZEGOVINA(CountryFlag.BOSNIA_AND_HERZEGOVINA, -1),
	BRAZIL(CountryFlag.BRAZIL, -1),
	BRUNEI(CountryFlag.BRUNEI, -1),
	BULGARIA(CountryFlag.BULGARIA, -1),
	CAMBODIA(CountryFlag.CAMBODIA, -1),
	CAMEROON(CountryFlag.CAMEROON, -1),
	CANADA(CountryFlag.CANADA, -8),
	CHILE(CountryFlag.CHILE, -1),
	CHINA(CountryFlag.CHINA, -1),
	COLOMBIA(CountryFlag.COLOMBIA, -1),
	COSTA_RICA(CountryFlag.COSTA_RICA, -1),
	CROATIA(CountryFlag.CROATIA, -1),
	CUBA(CountryFlag.CUBA, -1),
	CYPRUS(CountryFlag.CYPRUS, -1),
	CZECH_REPUBLIC(CountryFlag.CZECH_REPUBLIC, -1),
	DENMARK(CountryFlag.DENMARK, -1),
	DOMINICAN_REPUBLIC(CountryFlag.DOMINICAN_REPUBLIC, -1),
	ECUADOR(CountryFlag.ECUADOR, -1),
	EGYPT(CountryFlag.EGYPT, -1),
	EL_SALVADOR(CountryFlag.EL_SALVADOR, -1),
	ENGLAND(CountryFlag.ENGLAND, -1),
	ESTONIA(CountryFlag.ESTONIA, -1),
	ETHIOPIA(CountryFlag.ETHIOPIA, -1),
	EU(CountryFlag.EU, -1),
	FAROE_ISLANDS(CountryFlag.FAROE_ISLANDS, -1),
	FINLAND(CountryFlag.FINLAND, -1),
	FRANCE(CountryFlag.FRANCE, -1),
	GABON(CountryFlag.GABON, -1),
	GEORGIA(CountryFlag.GEORGIA, -1),
	GERMANY(CountryFlag.GERMANY, -1),
	GHANA(CountryFlag.GHANA, -1),
	GREECE(CountryFlag.GREECE, -1),
	GUATEMALA(CountryFlag.GUATEMALA, -1),
	HONDURAS(CountryFlag.HONDURAS, -1),
	HONG_KONG(CountryFlag.HONG_KONG, -1),
	HUNGARY(CountryFlag.HUNGARY, -1),
	ICELAND(CountryFlag.ICELAND, -1),
	INDIA(CountryFlag.INDIA, -1),
	INDONESIA(CountryFlag.INDONESIA, -1),
	IRAN(CountryFlag.IRAN, -1),
	IRAQ(CountryFlag.IRAQ, -1),
	IRELAND(CountryFlag.IRELAND, -1),
	ISLE_OF_MAN(CountryFlag.ISLE_OF_MAN, -1),
	ISRAEL(CountryFlag.ISRAEL, -1),
	ITALY(CountryFlag.ITALY, -1),
	IVORY_COAST(CountryFlag.IVORY_COAST, -1),
	JAMAICA(CountryFlag.JAMAICA, -1),
	JAPAN(CountryFlag.JAPAN, -1),
	JORDAN(CountryFlag.JORDAN, -1),
	KAZAKHSTAN(CountryFlag.KAZAKHSTAN, -1),
	KENYA(CountryFlag.KENYA, -1),
	KUWAIT(CountryFlag.KUWAIT, -1),
	KYRGYZSTAN(CountryFlag.KYRGYZSTAN, -1),
	LATVIA(CountryFlag.LATVIA, -1),
	LEBANON(CountryFlag.LEBANON, -1),
	LIBYA(CountryFlag.LIBYA, -1),
	LITHUANIA(CountryFlag.LITHUANIA, -1),
	LUXEMBOURG(CountryFlag.LUXEMBOURG, -1),
	MACAU(CountryFlag.MACAU, -1),
	MACEDONIA(CountryFlag.MACEDONIA, -1),
	MALAYSIA(CountryFlag.MALAYSIA, -1),
	MALTA(CountryFlag.MALTA, -1),
	MEXICO(CountryFlag.MEXICO, -1),
	MOLDOVA(CountryFlag.MOLDOVA, -1),
	MONGOLIA(CountryFlag.MONGOLIA, -1),
	MONTENEGRO(CountryFlag.MONTENEGRO, -1),
	MOROCCO(CountryFlag.MOROCCO, -1),
	MOZAMBIQUE(CountryFlag.MOZAMBIQUE, -1),
	NEPAL(CountryFlag.NEPAL, -1),
	NETHERLANDS(CountryFlag.NETHERLANDS, -1),
	NEW_ZEALAND(CountryFlag.NEW_ZEALAND, -1),
	NIGERIA(CountryFlag.NIGERIA, -1),
	NORWAY(CountryFlag.NORWAY, -1),
	OMAN(CountryFlag.OMAN, -1),
	PAKISTAN(CountryFlag.PAKISTAN, -1),
	PANAMA(CountryFlag.PANAMA, -1),
	PARAGUAY(CountryFlag.PARAGUAY, -1),
	PERU(CountryFlag.PERU, -1),
	PHILIPPINES(CountryFlag.PHILIPPINES, -1),
	POLAND(CountryFlag.POLAND, -1),
	PORTUGAL(CountryFlag.PORTUGAL, -1),
	PUERTO_RICO(CountryFlag.PUERTO_RICO, -1),
	QATAR(CountryFlag.QATAR, -1),
	ROMANIA(CountryFlag.ROMANIA, -1),
	RUSSIA(CountryFlag.RUSSIA, -1),
	RWANDA(CountryFlag.RWANDA, -1),
	SAUDI_ARABIA(CountryFlag.SAUDI_ARABIA, -1),
	SCOTLAND(CountryFlag.SCOTLAND, -1),
	SENEGAL(CountryFlag.SENEGAL, -1),
	SERBIA(CountryFlag.SERBIA, -1),
	SINGAPORE(CountryFlag.SINGAPORE, -1),
	SLOVAKIA(CountryFlag.SLOVAKIA, -1),
	SLOVENIA(CountryFlag.SLOVENIA, -1),
	SOLOMON_ISLANDS(CountryFlag.SOLOMON_ISLANDS, -1),
	SOMALIA(CountryFlag.SOMALIA, -1),
	SOUTH_AFRICA(CountryFlag.SOUTH_AFRICA, -1),
	SOUTH_KOREA(CountryFlag.SOUTH_KOREA, -1),
	SOUTH_SUDAN(CountryFlag.SOUTH_SUDAN, -1),
	SPAIN(CountryFlag.SPAIN, -1),
	SRI_LANKA(CountryFlag.SRI_LANKA, -1),
	SUDAN(CountryFlag.SUDAN, -1),
	SURINAME(CountryFlag.SURINAME, -1),
	SWEDEN(CountryFlag.SWEDEN, -1),
	SWITZERLAND(CountryFlag.SWITZERLAND, -1),
	SYRIA(CountryFlag.SYRIA, -1),
	TAIWAN(CountryFlag.TAIWAN, -1),
	TAJIKISTAN(CountryFlag.TAJIKISTAN, -1),
	TANZANIA(CountryFlag.TANZANIA, -1),
	THAILAND(CountryFlag.THAILAND, -1),
	TUNISIA(CountryFlag.TUNISIA, -1),
	TURKEY(CountryFlag.TURKEY, -1),
	UAE(CountryFlag.UAE, -1),
	UGANDA(CountryFlag.UGANDA, -1),
	UK(CountryFlag.UK, -1),
	UKRAINE(CountryFlag.UKRAINE, -1),
	URUGUAY(CountryFlag.URUGUAY, -1),
	USA(CountryFlag.USA, -8),
	UZBEKISTAN(CountryFlag.UZBEKISTAN, -1),
	VENEZUELA(CountryFlag.VENEZUELA, -1),
	VIETNAM(CountryFlag.VIETNAM, -1),
	WALES(CountryFlag.WALES, -1),
	YEMEN(CountryFlag.YEMEN, -1),
	ZAMBIA(CountryFlag.ZAMBIA, -1),
	ZIMBABWE(CountryFlag.ZIMBABWE, -1),

	;

	private final CountryFlag _flag;
	private final int _cost;

	FlagType(CountryFlag flag, int cost)
	{
		_flag = flag;
		_cost = cost;
	}

	public CountryFlag getFlag()
	{
		return _flag;
	}

	public int getCost()
	{
		return _cost;
	}
}
