/**
 * This class is generated by jOOQ
 */
package mineplex.database;

/**
 * Convenience access to all tables in Account
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Account.accountAmplifierThank
	 */
	public static final mineplex.database.tables.AccountAmplifierThank accountAmplifierThank = mineplex.database.tables.AccountAmplifierThank.accountAmplifierThank;

	/**
	 * The table Account.accountAuth
	 */
	public static final mineplex.database.tables.AccountAuth accountAuth = mineplex.database.tables.AccountAuth.accountAuth;

	/**
	 * The table Account.accountClan
	 */
	public static final mineplex.database.tables.AccountClan accountClan = mineplex.database.tables.AccountClan.accountClan;

	/**
	 * The table Account.accountCoinTransactions
	 */
	public static final mineplex.database.tables.AccountCoinTransactions accountCoinTransactions = mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions;

	/**
	 * The table Account.accountCustomData
	 */
	public static final mineplex.database.tables.AccountCustomData accountCustomData = mineplex.database.tables.AccountCustomData.accountCustomData;

	/**
	 * The table Account.accountFriend
	 */
	public static final mineplex.database.tables.AccountFriend accountFriend = mineplex.database.tables.AccountFriend.accountFriend;

	/**
	 * The table Account.accountGemTransactions
	 */
	public static final mineplex.database.tables.AccountGemTransactions accountGemTransactions = mineplex.database.tables.AccountGemTransactions.accountGemTransactions;

	/**
	 * The table Account.accountGiveaway
	 */
	public static final mineplex.database.tables.AccountGiveaway accountGiveaway = mineplex.database.tables.AccountGiveaway.accountGiveaway;

	/**
	 * The table Account.accountIgnore
	 */
	public static final mineplex.database.tables.AccountIgnore accountIgnore = mineplex.database.tables.AccountIgnore.accountIgnore;

	/**
	 * The table Account.accountInventory
	 */
	public static final mineplex.database.tables.AccountInventory accountInventory = mineplex.database.tables.AccountInventory.accountInventory;

	/**
	 * The table Account.accountMortenSpamTest
	 */
	public static final mineplex.database.tables.AccountMortenSpamTest accountMortenSpamTest = mineplex.database.tables.AccountMortenSpamTest.accountMortenSpamTest;

	/**
	 * The table Account.accountPets
	 */
	public static final mineplex.database.tables.AccountPets accountPets = mineplex.database.tables.AccountPets.accountPets;

	/**
	 * The table Account.accountPolls
	 */
	public static final mineplex.database.tables.AccountPolls accountPolls = mineplex.database.tables.AccountPolls.accountPolls;

	/**
	 * The table Account.accountPreferences
	 */
	public static final mineplex.database.tables.AccountPreferences accountPreferences = mineplex.database.tables.AccountPreferences.accountPreferences;

	/**
	 * The table Account.accountPurchases
	 */
	public static final mineplex.database.tables.AccountPurchases accountPurchases = mineplex.database.tables.AccountPurchases.accountPurchases;

	/**
	 * The table Account.accounts
	 */
	public static final mineplex.database.tables.Accounts accounts = mineplex.database.tables.Accounts.accounts;

	/**
	 * The table Account.accountStat
	 */
	public static final mineplex.database.tables.AccountStat accountStat = mineplex.database.tables.AccountStat.accountStat;

	/**
	 * The table Account.accountTasks
	 */
	public static final mineplex.database.tables.AccountTasks accountTasks = mineplex.database.tables.AccountTasks.accountTasks;

	/**
	 * The table Account.accountThank
	 */
	public static final mineplex.database.tables.AccountThank accountThank = mineplex.database.tables.AccountThank.accountThank;

	/**
	 * The table Account.accountThankTransactions
	 */
	public static final mineplex.database.tables.AccountThankTransactions accountThankTransactions = mineplex.database.tables.AccountThankTransactions.accountThankTransactions;

	/**
	 * The table Account.accountTip
	 */
	public static final mineplex.database.tables.AccountTip accountTip = mineplex.database.tables.AccountTip.accountTip;

	/**
	 * The table Account.accountTipClaimLogs
	 */
	public static final mineplex.database.tables.AccountTipClaimLogs accountTipClaimLogs = mineplex.database.tables.AccountTipClaimLogs.accountTipClaimLogs;

	/**
	 * The table Account.accountTipLogs
	 */
	public static final mineplex.database.tables.AccountTipLogs accountTipLogs = mineplex.database.tables.AccountTipLogs.accountTipLogs;

	/**
	 * The table Account.accountTransactions
	 */
	public static final mineplex.database.tables.AccountTransactions accountTransactions = mineplex.database.tables.AccountTransactions.accountTransactions;

	/**
	 * The table Account.accountValentinesGift
	 */
	public static final mineplex.database.tables.AccountValentinesGift accountValentinesGift = mineplex.database.tables.AccountValentinesGift.accountValentinesGift;

	/**
	 * The table Account.accountWebsiteLinkCode
	 */
	public static final mineplex.database.tables.AccountWebsiteLinkCode accountWebsiteLinkCode = mineplex.database.tables.AccountWebsiteLinkCode.accountWebsiteLinkCode;

	/**
	 * The table Account.activeTournaments
	 */
	public static final mineplex.database.tables.ActiveTournaments activeTournaments = mineplex.database.tables.ActiveTournaments.activeTournaments;

	/**
	 * The table Account.battlePets
	 */
	public static final mineplex.database.tables.BattlePets battlePets = mineplex.database.tables.BattlePets.battlePets;

	/**
	 * The table Account.bonus
	 */
	public static final mineplex.database.tables.Bonus bonus = mineplex.database.tables.Bonus.bonus;

	/**
	 * The table Account.bonusLog
	 */
	public static final mineplex.database.tables.BonusLog bonusLog = mineplex.database.tables.BonusLog.bonusLog;

	/**
	 * The table Account.botSpam
	 */
	public static final mineplex.database.tables.BotSpam botSpam = mineplex.database.tables.BotSpam.botSpam;

	/**
	 * The table Account.chatsnap
	 */
	public static final mineplex.database.tables.Chatsnap chatsnap = mineplex.database.tables.Chatsnap.chatsnap;

	/**
	 * The table Account.clanAlliances
	 */
	public static final mineplex.database.tables.ClanAlliances clanAlliances = mineplex.database.tables.ClanAlliances.clanAlliances;

	/**
	 * The table Account.clanBanners
	 */
	public static final mineplex.database.tables.ClanBanners clanBanners = mineplex.database.tables.ClanBanners.clanBanners;

	/**
	 * The table Account.clanBans
	 */
	public static final mineplex.database.tables.ClanBans clanBans = mineplex.database.tables.ClanBans.clanBans;

	/**
	 * The table Account.clanEnemies
	 */
	public static final mineplex.database.tables.ClanEnemies clanEnemies = mineplex.database.tables.ClanEnemies.clanEnemies;

	/**
	 * VIEW
	 */
	public static final mineplex.database.tables.ClanMember clanMember = mineplex.database.tables.ClanMember.clanMember;

	/**
	 * The table Account.clanNameBlacklist
	 */
	public static final mineplex.database.tables.ClanNameBlacklist clanNameBlacklist = mineplex.database.tables.ClanNameBlacklist.clanNameBlacklist;

	/**
	 * The table Account.clans
	 */
	public static final mineplex.database.tables.Clans clans = mineplex.database.tables.Clans.clans;

	/**
	 * The table Account.clanServer
	 */
	public static final mineplex.database.tables.ClanServer clanServer = mineplex.database.tables.ClanServer.clanServer;

	/**
	 * The table Account.clansGold
	 */
	public static final mineplex.database.tables.ClansGold clansGold = mineplex.database.tables.ClansGold.clansGold;

	/**
	 * The table Account.clanShopItem
	 */
	public static final mineplex.database.tables.ClanShopItem clanShopItem = mineplex.database.tables.ClanShopItem.clanShopItem;

	/**
	 * The table Account.clansNetherPortals
	 */
	public static final mineplex.database.tables.ClansNetherPortals clansNetherPortals = mineplex.database.tables.ClansNetherPortals.clansNetherPortals;

	/**
	 * The table Account.clansOutposts
	 */
	public static final mineplex.database.tables.ClansOutposts clansOutposts = mineplex.database.tables.ClansOutposts.clansOutposts;

	/**
	 * The table Account.clansPvpTimer
	 */
	public static final mineplex.database.tables.ClansPvpTimer clansPvpTimer = mineplex.database.tables.ClansPvpTimer.clansPvpTimer;

	/**
	 * The table Account.clansSiegeWeapons
	 */
	public static final mineplex.database.tables.ClansSiegeWeapons clansSiegeWeapons = mineplex.database.tables.ClansSiegeWeapons.clansSiegeWeapons;

	/**
	 * The table Account.clansTutorial
	 */
	public static final mineplex.database.tables.ClansTutorial clansTutorial = mineplex.database.tables.ClansTutorial.clansTutorial;

	/**
	 * The table Account.clanTerritory
	 */
	public static final mineplex.database.tables.ClanTerritory clanTerritory = mineplex.database.tables.ClanTerritory.clanTerritory;

	/**
	 * The table Account.clanWar
	 */
	public static final mineplex.database.tables.ClanWar clanWar = mineplex.database.tables.ClanWar.clanWar;

	/**
	 * The table Account.customData
	 */
	public static final mineplex.database.tables.CustomData customData = mineplex.database.tables.CustomData.customData;

	/**
	 * The table Account.eloRating
	 */
	public static final mineplex.database.tables.EloRating eloRating = mineplex.database.tables.EloRating.eloRating;

	/**
	 * The table Account.facebook
	 */
	public static final mineplex.database.tables.Facebook facebook = mineplex.database.tables.Facebook.facebook;

	/**
	 * The table Account.fieldBlock
	 */
	public static final mineplex.database.tables.FieldBlock fieldBlock = mineplex.database.tables.FieldBlock.fieldBlock;

	/**
	 * The table Account.fieldMonster
	 */
	public static final mineplex.database.tables.FieldMonster fieldMonster = mineplex.database.tables.FieldMonster.fieldMonster;

	/**
	 * The table Account.fieldOre
	 */
	public static final mineplex.database.tables.FieldOre fieldOre = mineplex.database.tables.FieldOre.fieldOre;

	/**
	 * The table Account.gadgets
	 */
	public static final mineplex.database.tables.Gadgets gadgets = mineplex.database.tables.Gadgets.gadgets;

	/**
	 * The table Account.giveaway
	 */
	public static final mineplex.database.tables.Giveaway giveaway = mineplex.database.tables.Giveaway.giveaway;

	/**
	 * The table Account.giveawayCooldown
	 */
	public static final mineplex.database.tables.GiveawayCooldown giveawayCooldown = mineplex.database.tables.GiveawayCooldown.giveawayCooldown;

	/**
	 * The table Account.incognitoStaff
	 */
	public static final mineplex.database.tables.IncognitoStaff incognitoStaff = mineplex.database.tables.IncognitoStaff.incognitoStaff;

	/**
	 * The table Account.itemCategories
	 */
	public static final mineplex.database.tables.ItemCategories itemCategories = mineplex.database.tables.ItemCategories.itemCategories;

	/**
	 * The table Account.items
	 */
	public static final mineplex.database.tables.Items items = mineplex.database.tables.Items.items;

	/**
	 * The table Account.kitpreferences
	 */
	public static final mineplex.database.tables.Kitpreferences kitpreferences = mineplex.database.tables.Kitpreferences.kitpreferences;

	/**
	 * The table Account.kitProgression
	 */
	public static final mineplex.database.tables.KitProgression kitProgression = mineplex.database.tables.KitProgression.kitProgression;

	/**
	 * The table Account.mail
	 */
	public static final mineplex.database.tables.Mail mail = mineplex.database.tables.Mail.mail;

	/**
	 * The table Account.mailbox
	 */
	public static final mineplex.database.tables.Mailbox mailbox = mineplex.database.tables.Mailbox.mailbox;

	/**
	 * The table Account.nonPremiumJoinMessage
	 */
	public static final mineplex.database.tables.NonPremiumJoinMessage nonPremiumJoinMessage = mineplex.database.tables.NonPremiumJoinMessage.nonPremiumJoinMessage;

	/**
	 * The table Account.npcs
	 */
	public static final mineplex.database.tables.Npcs npcs = mineplex.database.tables.Npcs.npcs;

	/**
	 * The table Account.packages
	 */
	public static final mineplex.database.tables.Packages packages = mineplex.database.tables.Packages.packages;

	/**
	 * The table Account.playerMap
	 */
	public static final mineplex.database.tables.PlayerMap playerMap = mineplex.database.tables.PlayerMap.playerMap;

	/**
	 * The table Account.polls
	 */
	public static final mineplex.database.tables.Polls polls = mineplex.database.tables.Polls.polls;

	/**
	 * The table Account.powerPlayClub
	 */
	public static final mineplex.database.tables.PowerPlayClub powerPlayClub = mineplex.database.tables.PowerPlayClub.powerPlayClub;

	/**
	 * The table Account.rankBenefits
	 */
	public static final mineplex.database.tables.RankBenefits rankBenefits = mineplex.database.tables.RankBenefits.rankBenefits;

	/**
	 * The table Account.rankedBans
	 */
	public static final mineplex.database.tables.RankedBans rankedBans = mineplex.database.tables.RankedBans.rankedBans;

	/**
	 * The table Account.reportTickets
	 */
	public static final mineplex.database.tables.ReportTickets reportTickets = mineplex.database.tables.ReportTickets.reportTickets;

	/**
	 * The table Account.selectedgadgets
	 */
	public static final mineplex.database.tables.Selectedgadgets selectedgadgets = mineplex.database.tables.Selectedgadgets.selectedgadgets;

	/**
	 * The table Account.selectedmodifiers
	 */
	public static final mineplex.database.tables.Selectedmodifiers selectedmodifiers = mineplex.database.tables.Selectedmodifiers.selectedmodifiers;

	/**
	 * The table Account.selectedMounts
	 */
	public static final mineplex.database.tables.SelectedMounts selectedMounts = mineplex.database.tables.SelectedMounts.selectedMounts;

	/**
	 * The table Account.selectedPets
	 */
	public static final mineplex.database.tables.SelectedPets selectedPets = mineplex.database.tables.SelectedPets.selectedPets;

	/**
	 * The table Account.serverPassword
	 */
	public static final mineplex.database.tables.ServerPassword serverPassword = mineplex.database.tables.ServerPassword.serverPassword;

	/**
	 * The table Account.spawns
	 */
	public static final mineplex.database.tables.Spawns spawns = mineplex.database.tables.Spawns.spawns;

	/**
	 * The table Account.staffMotd
	 */
	public static final mineplex.database.tables.StaffMotd staffMotd = mineplex.database.tables.StaffMotd.staffMotd;

	/**
	 * The table Account.statEvents
	 */
	public static final mineplex.database.tables.StatEvents statEvents = mineplex.database.tables.StatEvents.statEvents;

	/**
	 * The table Account.stats
	 */
	public static final mineplex.database.tables.Stats stats = mineplex.database.tables.Stats.stats;

	/**
	 * Stores a reference of the various types of statistics and their associated stat type IDs.
	 */
	public static final mineplex.database.tables.StatTypes statTypes = mineplex.database.tables.StatTypes.statTypes;

	/**
	 * The table Account.streamers
	 */
	public static final mineplex.database.tables.Streamers streamers = mineplex.database.tables.Streamers.streamers;

	/**
	 * The table Account.tasks
	 */
	public static final mineplex.database.tables.Tasks tasks = mineplex.database.tables.Tasks.tasks;

	/**
	 * The table Account.titanGiveaway
	 */
	public static final mineplex.database.tables.TitanGiveaway titanGiveaway = mineplex.database.tables.TitanGiveaway.titanGiveaway;

	/**
	 * The table Account.TournamentLB
	 */
	public static final mineplex.database.tables.TournamentLB TournamentLB = mineplex.database.tables.TournamentLB.TournamentLB;

	/**
	 * The table Account.tournaments
	 */
	public static final mineplex.database.tables.Tournaments tournaments = mineplex.database.tables.Tournaments.tournaments;

	/**
	 * The table Account.tournamentTeams
	 */
	public static final mineplex.database.tables.TournamentTeams tournamentTeams = mineplex.database.tables.TournamentTeams.tournamentTeams;

	/**
	 * The table Account.transactions
	 */
	public static final mineplex.database.tables.Transactions transactions = mineplex.database.tables.Transactions.transactions;

	/**
	 * The table Account.unicodereplacer
	 */
	public static final mineplex.database.tables.Unicodereplacer unicodereplacer = mineplex.database.tables.Unicodereplacer.unicodereplacer;

	/**
	 * The table Account.youtube
	 */
	public static final mineplex.database.tables.Youtube youtube = mineplex.database.tables.Youtube.youtube;
}
